KiBoard GDD & Technical Documentation: MidiInput Class Reference
MidiInput Class Reference
Public Member Functions
void LoadScenePreview (string sceneName)
Loads a preview of selected song into the currentPreview Scene variable, and begins playing the songs preview.
void LoadSongFromCurrentSettings (bool isPreview=false)
Loads the selected song for gameplay.
void HookMidiDevice ()
Hooks midi devices to be used for input.
void UnHookMidiDevice ()
unhooks midi devices to remove their input.
NoteEventDataWrapper GetNoteEventWrapperFromSelectedSong ()
void StartSongCoroutine ()
called to begin playing the song.
IEnumerator StartSong (bool isPreview=false)
Starts playing the loaded song using the current FileGroup's mp3 file field.
IEnumerator StartSong (string mp3Path, bool isPreview=false)
Starts playing the loaded song from a given file path.
IEnumerator StartSong (List< NoteEventInfo > loadEvents, bool isPreview=false)
Starts playing a specified list of NoteEventInfo
void StopSong ()
Stops the currently playing song.
void OnNoteSuccess (ref string score, int note, float timing, NoteEventInfo storedNote)
Handles successful note presses.
bool IsNoteCorrect (int noteNumber, float timing, NoteEventInfo storedNote)
Check if note is was played at a correct timing.
void RetryCurrentSong ()
Reloads the currently playing song.
bool GetAnyNoteActive ()
Checks for pressed keys in the 8-key keyboard layout.
string GetTimingScore (float timing)
Gets the timing score based on the timing difference.
Public Attributes
List< NoteEventInfo > storedNoteEvents
Currently loaded notes for the selected song.
Coroutine PrepareNotesCoroutine
Reference to the GameManager.PrepareNotes(float, List<NoteEventInfo>, bool) prepareNotes Coroutine.
bool isPedalPressed
Is the pedal pressed.
bool[] enabledKeys = new bool[88]
array of bools corresponding to currently activated keys.
bool takeInput = true
Should the game take piano input.
bool inGame = false
Are we in the game scene.
bool isMidiHooked
are midi devices hooked?
HookMidiDevice and UnHookMidiDevice.
RenderTexture renderTexture
Render texture used for previewing scenes in Song Selection.
Scene currentPreview
Scene used for previewing songs in Song Selection.
Static Public Attributes
static MidiInput instance
Private Member Functions
void Awake ()
void Update ()
void PedalStateChanged (MidiChannel channel, int knobNumber, float knobValue)
Handles MIDI sustain pedal state changes.
void NoteOn (MidiChannel channel, int note, float velocity)
Handles MIDI note on events.
void NoteOff (MidiChannel channel, int note)
Handles MIDI note off events.
void CheckNotesKeyboard12 ()
Checks for pressed keys in the 12-key keyboard layout.
float GetTimeDifference (float storedTiming)
Calculates the time difference between the stored timing and the current song time.
Private Attributes
GameObject imagePrefab
keyPrefab object with a RawImage component to assign renderTexture to.
Dictionary< KeyCode, int > keyboard12
Dictionary mapping for Computer keyboard input to note input.
Member Function Documentation
Awake()
void MidiInput.Awake () private
    {
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else { Destroy(gameObject); }
    }
CheckNotesKeyboard12()
void MidiInput.CheckNotesKeyboard12 () private
Checks for pressed keys in the 12-key keyboard layout.
    {
        // Check for computer keyboard key presses and releases
        foreach (var keyValuePair in keyboard12)
        {
            KeyCode key = keyValuePair.Key;
            int noteNumber = keyValuePair.Value;
            if (Input.GetKeyDown(key))
            {
                // Simulate Note On event for the pressed key
                NoteOn(MidiChannel.All, noteNumber, 1.0f);
            }
            if (Input.GetKeyUp(key))
            {
                // Simulate Note Off event for the released key
                NoteOff(MidiChannel.All, noteNumber);
            }
        }
    }
Referenced by Update().
GetAnyNoteActive()
bool MidiInput.GetAnyNoteActive ()
Checks for pressed keys in the 8-key keyboard layout.
Checks if any note is currently active (pressed).
Returns
True if any note is active, otherwise false.
    {
        foreach (bool b in enabledKeys)
        {
            if (b)
            {
                return true;
            }
        }
        return false;
    }
GetNoteEventWrapperFromSelectedSong()
NoteEventDataWrapper MidiInput.GetNoteEventWrapperFromSelectedSong ()
Returns
NoteEventDataWrapper loaded from the currently selected song
    {
        NoteEventDataWrapper data = MidiReadFile.GetNoteEventsFromFilePath(GameSettings.currentSongPath);
        if (data == null) { Debug.Log("Error Reading data from path: " + GameSettings.currentSongPath); return null; }
        storedNoteEvents = data.NoteEvents;
        return data;
    }
GetTimeDifference()
float MidiInput.GetTimeDifference (float storedTiming) private
Calculates the time difference between the stored timing and the current song time.
Parameters
storedTiming The stored timing value.
Returns
The time difference.
    {
        // Adjust this threshold based on your timing accuracy requirements
        // float timingThreshold = currentSettings.timeInterval;
        // Check if the received timing is within a certain threshold of the stored timing
        //0.125f leniancy
        return Mathf.Abs( (GameManager.instance.songTime + PlayerSettings.inputDelay)  - 0.125f - storedTiming);
    }
Referenced by NoteOn().
GetTimingScore()
string MidiInput.GetTimingScore (float timing)
Gets the timing score based on the timing difference.
Parameters
timing The timing difference.
Returns
The timing score (e.g., "Perfect", "Good", "Okay", "Miss").
    {
        if (timing < 0.1f) { return "Perfect"; }
        else if (timing < 0.175f) { return "Good"; }
        else if (timing < 0.275f) { return "Okay"; }
        else { return "Miss"; }
    }
Referenced by NoteOn(), and OnNoteSuccess().
HookMidiDevice()
void MidiInput.HookMidiDevice ()
Hooks midi devices to be used for input.
    {
        try
        {
            if (isMidiHooked) { Debug.Log("Midi Already Hooked"); return; }
            MidiMaster.noteOnDelegate += NoteOn;
            MidiMaster.noteOffDelegate += NoteOff;
            MidiMaster.knobDelegate += PedalStateChanged;
            isMidiHooked = true;
        }
        catch
        {
            isMidiHooked = false;
            Debug.Log("Error Hooking midi device");
        }
    }
Referenced by LoadSongFromCurrentSettings().
IsNoteCorrect()
bool MidiInput.IsNoteCorrect (int noteNumber, float timing, NoteEventInfo storedNote)
Check if note is was played at a correct timing.
Parameters
noteNumber Number of the note played.
timing What time the note was hit.
storedNote Note that is being compared to.
Returns
    {
        if (GameSettings.usePiano) { return noteNumber == storedNote.noteNumber && !storedNote.triggered && timing < 0.5f; }
        return noteNumber % 12 == storedNote.noteNumber % 12 && !storedNote.triggered && timing < 0.5f;
    }
Referenced by NoteOn().
LoadScenePreview()
void MidiInput.LoadScenePreview (string sceneName)
Loads a preview of selected song into the currentPreview Scene variable, and begins playing the songs preview.
Parameters
sceneName
    {
        if (currentPreview.isLoaded)
        {
            SceneManager.UnloadSceneAsync(currentPreview);
        }
        AsyncOperation loadOperation = SceneManager.LoadSceneAsync(sceneName, LoadSceneMode.Additive);
        loadOperation.completed += (operation) =>
        {
            currentPreview = SceneManager.GetSceneByName(sceneName); // Assign the loaded scene to currentPreview
            OnSceneLoaded(operation);
        };
        void OnSceneLoaded(AsyncOperation asyncOperation)
        {
            Scene previewScene = SceneManager.GetSceneByName(sceneName);
            // Iterate through the root game objects of the scene
            foreach (GameObject rootObject in previewScene.GetRootGameObjects())
            {
                if (rootObject.TryGetComponent(out TransitionManager transition))
                {
                    transition.GetComponent<Canvas>().enabled = false;
                }
                if (rootObject.TryGetComponent(out Canvas canvas))
                {
                    canvas.enabled = false;
                }
                // Assign the object to the "PreviewLayer"
                AssignToPreviewLayer(rootObject);
                // Check if the object has an EventSystem component and destroy it
                if (rootObject.TryGetComponent(out EventSystem eventSystem))
                {
                    Destroy(eventSystem.gameObject);
                }
                // Find the camera in the preview scene
                Camera camera = rootObject.GetComponentInChildren<Camera>();
                if (camera != null)
                {
                    // Set the camera to render to the specified RenderTexture
                    camera.cullingMask = 1 << LayerMask.NameToLayer("PreviewLayer");
                    camera.targetTexture = renderTexture;
                }
            }
            // Create a new UI Image object
            GameObject imageObject = Instantiate(imagePrefab, UiHolder.instance.transform);
            RawImage image = imageObject.GetComponentInChildren<RawImage>(); // CAN ONLY DO THIS BECAUSE IT IS RAWIMAGE, SINCE I USE MANY NORMAL IMAGE TYPES.
            // Check if RawImage component exists
            if (image != null)
            {
                // Assign the RenderTexture to the RawImage component's texture
                image.texture = renderTexture;
                if (UiHolder.instance.scenePreview != null) { Destroy(UiHolder.instance.scenePreview); }
                UiHolder.instance.scenePreview = imageObject;
            }
            else
            {
                Debug.LogError("RawImage component not found on the instantiated image prefab.");
            }
            asyncOperation.completed -= OnSceneLoaded;
        }
        // Method to assign an object and its children to the "PreviewLayer"
        void AssignToPreviewLayer(GameObject obj)
        {
            // Assign the object to the "PreviewLayer"
            obj.layer = LayerMask.NameToLayer("PreviewLayer");
            // Recursively assign children to the "PreviewLayer"
            foreach (Transform child in obj.transform)
            {
                AssignToPreviewLayer(child.gameObject);
            }
        }
    }
Referenced by LoadSongFromCurrentSettings().
LoadSongFromCurrentSettings()
void MidiInput.LoadSongFromCurrentSettings (bool isPreview = false)
Loads the selected song for gameplay.
    {
        MP3Handler.instance.StopMusic();
        string gameMode;
        if (KiboardDebug.isMidiConnected && GameSettings.usePiano) { gameMode = "GameScene88"; } else { gameMode = "GameScene12"; }
        if (isPreview)
        {
            LoadScenePreview(gameMode);
            NoteEventDataWrapper data = MidiReadFile.GetNoteEventsFromFilePath(GameSettings.currentSongPath);
            GameSettings.bpm = data.BPM;
            storedNoteEvents = data.NoteEvents;
            takeInput = false;
            inGame = false;
            StartCoroutine(StartSong(true));
        }
        else
        {
            try
            {
                TransitionManager.instance.LoadNewScene(gameMode);
            }
            catch(Exception e)
            {
                Debug.Log(e);
                SceneManager.LoadScene(gameMode);
            }
            if (GameSettings.usePiano) { HookMidiDevice(); } else { UnHookMidiDevice(); }
            NoteEventDataWrapper data = MidiReadFile.GetNoteEventsFromFilePath(GameSettings.currentSongPath);
            GameSettings.bpm = GameSettings.bpm == 0 ? data.BPM : GameSettings.bpm;
            storedNoteEvents = data.NoteEvents;
            takeInput = true;
            inGame = true;
            if (PrepareNotesCoroutine != null) StopCoroutine(PrepareNotesCoroutine);
            GameManager.instance.StopReadiedNotes();
            StartCoroutine(StartSong());
        }
    }
Referenced by RetryCurrentSong().
NoteOff()
void MidiInput.NoteOff (MidiChannel channel, int note) private
Handles MIDI note off events.
Parameters
channel The MIDI channel.
note The MIDI note number.
    {
        if (!takeInput || isPedalPressed) { return; }
        if (inGame)
        {
            SpawnPiano.instance.UpdateKeyColours(note - 21, false);
            Replay.UpdateReplay(note, GameManager.instance.songTime);
        }
        enabledKeys[note - 21] = false;
    }
Referenced by CheckNotesKeyboard12(), HookMidiDevice(), and UnHookMidiDevice().
NoteOn()
void MidiInput.NoteOn (MidiChannel channel, int note, float velocity) private
Handles MIDI note on events.
Parameters
channel The MIDI channel.
note The MIDI note number.
velocity The note velocity.
    {
        if (!takeInput) { return; }
        // Check if the received note and timing match any stored events
        if (inGame)
        {
            string score = "";
            float timing = Mathf.Infinity;
            foreach (NoteEventInfo storedNote in storedNoteEvents)
            {
                if (storedNoteEvents == null) { return; }
                timing = GetTimeDifference(storedNote.startTime);
                if (IsNoteCorrect(note, timing, storedNote))
                {
                    OnNoteSuccess(ref score, note, timing, storedNote);
                    break;  // Exit the loop after the first match
                }
            }
            score ??= GetTimingScore(timing);
            GameManager.instance.combo.ChangeMultiplier(score);
            SpawnPiano.instance.UpdateKeyColours(note - 21, true, score);
            if (GameManager.instance.songTime >= 0)
            {
                GameManager.instance.UpdatePlayerScore(score);
            }
            Replay.UpdateReplay(note, GameManager.instance.songTime);
        }
        enabledKeys[note - 21] = true;
    }
Referenced by CheckNotesKeyboard12(), HookMidiDevice(), and UnHookMidiDevice().
OnNoteSuccess()
void MidiInput.OnNoteSuccess (ref string score, int note, float timing, NoteEventInfo storedNote)
Handles successful note presses.
Parameters
score
note
timing
storedNote
    {
        score = GetTimingScore(timing);
        SpawnPiano.instance.SpawnKeyParticle(note - 21, score);
        storedNote.triggered = true;
    }
Referenced by NoteOn().
PedalStateChanged()
void MidiInput.PedalStateChanged (MidiChannel channel, int knobNumber, float knobValue) private
Handles MIDI sustain pedal state changes.
Parameters
channel The MIDI channel.
knobNumber The knob number.
knobValue The knob value.
    {
        if (knobNumber == 64 && knobValue > 0.5f)
        {
            isPedalPressed = true;
        }
        else
        {
            isPedalPressed = false;
            try { SpawnPiano.instance.ClearAllKeyColours(); }
            catch { }
        }
    }
Referenced by HookMidiDevice(), and UnHookMidiDevice().
RetryCurrentSong()
void MidiInput.RetryCurrentSong ()
Reloads the currently playing song.
    {
        UnHookMidiDevice();
        LoadSongFromCurrentSettings(false);
    }
StartSong() [1/3]
IEnumerator MidiInput.StartSong (bool isPreview = false)
Starts playing the loaded song using the current FileGroup's mp3 file field.
Returns
    {
        GameManager.instance.currentSongScore.ClearScore();
        GameManager.instance.combo.ClearCombo();
        yield return PrepareNotesCoroutine = StartCoroutine(GameManager.instance.PrepareNotes(GameSettings.bpm, storedNoteEvents, isPreview));
        StartCoroutine(MP3Handler.instance.PlaySong(SongSelection.GetUnderscoreSubstring(GameSettings.currentFileGroup.Mp3File)));
    }
Referenced by LoadSongFromCurrentSettings(), and StartSongCoroutine().
StartSong() [2/3]
IEnumerator MidiInput.StartSong (List< NoteEventInfo > loadEvents, bool isPreview = false)
Starts playing a specified list of NoteEventInfo
Parameters
loadEvents The list of note events to play.
Returns
    {
        GameManager.instance.currentSongScore.ClearScore();
        var bpm = GameSettings.bpm;
        loadEvents.ForEach(noteEvent => noteEvent.noteNumber += 20); // i - for the fucking life of me- cannot figure out why directly processing the midi files makes the note numbers
                                                                     // 20 higher, but i have to do this to match that with the song editor.
        yield return PrepareNotesCoroutine = StartCoroutine(GameManager.instance.PrepareNotes(GameSettings.bpm, storedNoteEvents, isPreview));
        StartCoroutine(MP3Handler.instance.PlaySong(GameSettings.currentSongPath));
    }
StartSong() [3/3]
IEnumerator MidiInput.StartSong (string mp3Path, bool isPreview = false)
Starts playing the loaded song from a given file path.
Returns
    {
        GameManager.instance.currentSongScore.ClearScore();
        GameManager.instance.combo.ClearCombo();
        yield return PrepareNotesCoroutine = StartCoroutine(GameManager.instance.PrepareNotes(GameSettings.bpm, storedNoteEvents, isPreview));
        StartCoroutine(MP3Handler.instance.PlaySong(mp3Path));
    }
StartSongCoroutine()
void MidiInput.StartSongCoroutine ()
called to begin playing the song.
    {
        StartCoroutine(StartSong());
    }
StopSong()
void MidiInput.StopSong ()
Stops the currently playing song.
    {
        if (GameManager.instance.isCurSongPreview) { return; }
        GameManager.instance.StopSong();
        StopCoroutine(PrepareNotesCoroutine);
        MP3Handler.instance.StopMusic();
        GameSettings.ResetSettings(false);
        GameManager.instance.ReturnToSongSelection();
    }
Referenced by Update().
UnHookMidiDevice()
void MidiInput.UnHookMidiDevice ()
unhooks midi devices to remove their input.
    {
        try
        {
            MidiMaster.noteOnDelegate -= NoteOn;
            MidiMaster.noteOffDelegate -= NoteOff;
            MidiMaster.knobDelegate -= PedalStateChanged;
            isMidiHooked = false;
        }
        catch
        {
            isMidiHooked = false;
            Debug.Log("Error Unhooking midi device");
        }
    }
Referenced by LoadSongFromCurrentSettings(), and RetryCurrentSong().
Update()
void MidiInput.Update () private
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            StopSong();
        }
        CheckNotesKeyboard12();
        //CheckNotesKeyboard8();
    }
Member Data Documentation
currentPreview
Scene MidiInput.currentPreview
Scene used for previewing songs in Song Selection.
Referenced by LoadScenePreview().
enabledKeys
bool [] MidiInput.enabledKeys = new bool[88]
array of bools corresponding to currently activated keys.
Referenced by GetAnyNoteActive(), NoteOff(), and NoteOn().
imagePrefab
GameObject MidiInput.imagePrefab private
keyPrefab object with a RawImage component to assign renderTexture to.
Referenced by LoadScenePreview().
inGame
bool MidiInput.inGame = false
Are we in the game scene.
Referenced by LoadSongFromCurrentSettings(), NoteOff(), and NoteOn().
instance
MidiInput MidiInput.instance static
Referenced by GameManager.AssignToPreviewLayer(), Awake(), MainMenuLoad.LoadToSongSelect(), GameManager.PrepareNotes(), and GameManager.ReturnToSongSelection().
isMidiHooked
bool MidiInput.isMidiHooked
are midi devices hooked?
HookMidiDevice and UnHookMidiDevice.
Referenced by HookMidiDevice(), and UnHookMidiDevice().
isPedalPressed
bool MidiInput.isPedalPressed
Is the pedal pressed.
Referenced by NoteOff(), and PedalStateChanged().
keyboard12
Dictionary<KeyCode, int> MidiInput.keyboard12 private
Initial value:
= new Dictionary<KeyCode, int>
    {
        { KeyCode.A, 48 },
        { KeyCode.W, 49 },
        { KeyCode.S, 50 },
        { KeyCode.E, 51 },
        { KeyCode.D, 52 },
        { KeyCode.F, 53 },
        { KeyCode.T, 54 },
        { KeyCode.G, 55 },
        { KeyCode.Y, 56 },
        { KeyCode.H, 57 },
        { KeyCode.U, 58 },
        { KeyCode.J, 59 },
    }
Dictionary mapping for Computer keyboard input to note input.
    {
        { KeyCode.A, 48 },
        { KeyCode.W, 49 },
        { KeyCode.S, 50 },
        { KeyCode.E, 51 },
        { KeyCode.D, 52 },
        { KeyCode.F, 53 },
        { KeyCode.T, 54 },
        { KeyCode.G, 55 },
        { KeyCode.Y, 56 },
        { KeyCode.H, 57 },
        { KeyCode.U, 58 },
        { KeyCode.J, 59 },
    };
Referenced by CheckNotesKeyboard12().
PrepareNotesCoroutine
Coroutine MidiInput.PrepareNotesCoroutine
Reference to the GameManager.PrepareNotes(float, List<NoteEventInfo>, bool) prepareNotes Coroutine.
Referenced by LoadSongFromCurrentSettings(), StartSong(), StartSong(), StartSong(), and StopSong().
renderTexture
RenderTexture MidiInput.renderTexture
Render texture used for previewing scenes in Song Selection.
Referenced by LoadScenePreview().
storedNoteEvents
List<NoteEventInfo> MidiInput.storedNoteEvents
Currently loaded notes for the selected song.
Referenced by GetNoteEventWrapperFromSelectedSong(), LoadSongFromCurrentSettings(), NoteOn(), StartSong(), StartSong(), and StartSong().
takeInput
bool MidiInput.takeInput = true
Should the game take piano input.
Referenced by LoadSongFromCurrentSettings(), NoteOff(), and NoteOn().
The documentation for this class was generated from the following file:
Assets/Scripts/MidiInput.cs