KiBoard GDD & Technical Documentation: EditorAction Class Reference
EditorAction Class Reference
Base EditorAction for other more specific actions to inherit from.
Classes
struct NoteWrapper
SongEditor Struct to keep initial position and editornotes easily accessable.
Public Member Functions
EditorAction SetEditorAction (sbyte mouseNum)
Returns a pre existing editoraction and allows you to set the button used to activate it at the same time.
virtual void HandleInput ()
calls all other input methods (down,hold,up,scrollwheel).
virtual void Reset ()
Protected Member Functions
virtual void Down ()
Called on MouseButtonDown()
virtual void Hold ()
Called on MouseButton() (excludes first frame pressed)
virtual void Up ()
Called on MouseButtonUp()
virtual void ScrollWheel ()
bool GetMouseRaycast (out RaycastHit2D hit)
Sends raycast from Camera.main to mouse position and assigns the raycasthit2d to hit.
bool CheckDown ()
bool CheckHold ()
bool CheckUp ()
Protected Attributes
sbyte mouseButton
RaycastHit2D hit
Detailed Description
Base EditorAction for other more specific actions to inherit from.
Member Function Documentation
CheckDown()
bool EditorAction.CheckDown () protected
{ return !Input.GetMouseButtonDown(mouseButton); }// return true if mouse button not down on this frame.
Referenced by CheckHold(), AddNote.Down(), MoveNotes.Down(), RemoveNotes.Down(), and SelectNotes.Down().
CheckHold()
bool EditorAction.CheckHold () protected
{ return !Input.GetMouseButton(mouseButton) && CheckDown(); }// return true if mouse button not held and if checkdown()
Referenced by MoveNotes.Hold(), RemoveNotes.Hold(), and SelectNotes.Hold().
CheckUp()
bool EditorAction.CheckUp () protected
{ return !Input.GetMouseButtonUp(mouseButton); } //retun true if mouse button not up on this frame.
Referenced by MoveNotes.Up().
Down()
virtual void EditorAction.Down () protected virtual
Called on MouseButtonDown()
Reimplemented in AddNote, MoveNotes, RemoveNotes, and SelectNotes.
    {
        // used for overrides
    }
Referenced by HandleInput().
GetMouseRaycast()
bool EditorAction.GetMouseRaycast (out RaycastHit2D hit) protected
Sends raycast from Camera.main to mouse position and assigns the raycasthit2d to hit.
Returns
Whether or not the raycast hit an object.
    {
        hit = Physics2D.Raycast(Camera.main.ScreenToWorldPoint(Input.mousePosition), Vector2.zero);
        return hit;
    }
Referenced by HandleInput(), and MoveNotes.Hold().
HandleInput()
virtual void EditorAction.HandleInput () virtual
calls all other input methods (down,hold,up,scrollwheel).
    {
        if (GetMouseRaycast(out hit))
        {
            Down();
            Hold();
            Up();
        }
        ScrollWheel();
    }
Referenced by SongEditor.Update().
Hold()
virtual void EditorAction.Hold () protected virtual
Called on MouseButton() (excludes first frame pressed)
Reimplemented in AddNote, MoveNotes, RemoveNotes, and SelectNotes.
    {
        // used for overrides
    }
Referenced by HandleInput().
Reset()
virtual void EditorAction.Reset () virtual
    {
    }
ScrollWheel()
virtual void EditorAction.ScrollWheel () protected virtual
Reimplemented in ScaleNotes.
    {
        // used for overrides
    }
Referenced by HandleInput().
SetEditorAction()
EditorAction EditorAction.SetEditorAction (sbyte mouseNum)
Returns a pre existing editoraction and allows you to set the button used to activate it at the same time.
Parameters
mouseNum new mouse number assigned to the editor action.
Returns
editor action.
    {
        if (mouseNum < 0 || mouseNum >= 3) { mouseButton = -1; }
        mouseButton = mouseNum;
        return this;
    }
Referenced by SongEditor.InitializeAction().
Up()
virtual void EditorAction.Up () protected virtual
Called on MouseButtonUp()
Reimplemented in MoveNotes.
    {
        // used for overrides
    }
Referenced by HandleInput().
Member Data Documentation
hit
RaycastHit2D EditorAction.hit protected
Referenced by AddNote.CreateNote(), AddNote.Down(), MoveNotes.Down(), GetMouseRaycast(), HandleInput(), RemoveNotes.RemoveNoteIfHit(), ScaleNotes.ScaleNote(), and SelectNotes.SelectNote().
mouseButton
sbyte EditorAction.mouseButton protected
Referenced by CheckDown(), CheckHold(), CheckUp(), and SetEditorAction().
The documentation for this class was generated from the following file:
Assets/Scripts/SongEditor.cs