KiBoard GDD & Technical Documentation: GameUI Class Reference
GameUI Class Reference
Public Member Functions
void CreateTimingText (int score, string scoretext)
creates a different timing text based on the timing score.
void SetComboBarValue (float value)
sets the value of the combo bar slider based off of the current combo's multiplier.
Static Public Attributes
static GameUI instance
Private Member Functions
void Awake ()
void Update ()
void SpawnTimingText (string score, Color color)
spawns timing score text above the score.
IEnumerator FadeoutDestroy (TextMeshProUGUI textMesh)
Fades out the alpha of text object and destroys the text's gameObject after a delay.
Private Attributes
GameObject textPrefab
float fadeoutTimer
TextMeshProUGUI scoreText
TextMeshProUGUI comboText
Slider comboBar
Gradient comboGradient
Member Function Documentation
Awake()
void GameUI.Awake () private
    {
        if (instance == null)
        {
            instance = this;
        }
        else { Destroy(this); }
    }
CreateTimingText()
void GameUI.CreateTimingText (int score, string scoretext)
creates a different timing text based on the timing score.
    {
        Color textColor;
        string scoreString = Mathf.Sign(score) >= 0 ? "+" : "";
        scoreString += score.ToString();
        switch (scoretext)
        {
            case "Perfect":
                textColor = new Color(1, 0, 0.75f, .5f);
                break;
            case "Good":
                textColor = new Color(0.15f, 1, .5f, .5f);
                break;
            case "Okay":
                textColor = new Color(0, 0.04f, 1, .5f);
                break;
            default:
                textColor= new Color(1, 0, 0, .5f);
                break;
        }
        SpawnTimingText(scoreString, textColor);
        scoreText.text = GameManager.instance.currentSongScore.score.ToString();
    }
FadeoutDestroy()
IEnumerator GameUI.FadeoutDestroy (TextMeshProUGUI textMesh) private
Fades out the alpha of text object and destroys the text's gameObject after a delay.
Parameters
textMesh
Returns
    {
        Color startColor = textMesh.color; // Get the initial color
        Color targetColor = new(startColor.r, startColor.g, startColor.b, 0); // Target color with alpha set to 0
        float elapsedTime = 0f;
        while (elapsedTime < fadeoutTimer)
        {
            Color temp;
            // Assign the new color back to the TextMeshProUGUI
            textMesh.color = temp = Color.Lerp(startColor, targetColor, elapsedTime / fadeoutTimer);
            elapsedTime += Time.deltaTime;
            yield return null;
        }
        // Ensure that the final color is set to the targetColor
        textMesh.color = targetColor;
        // Perform any other actions or destroy the TextMeshProUGUI object
        Destroy(textMesh.gameObject);
    }
Referenced by SpawnTimingText().
SetComboBarValue()
void GameUI.SetComboBarValue (float value)
sets the value of the combo bar slider based off of the current combo's multiplier.
Parameters
value
    {
        // Assuming the input value ranges from 1 to 3
        float normalizedValue = (value - 1) / (3 - 1);
        float roundedNormalizedValue = Mathf.Round(value * 10) / 10;
        comboBar.value = normalizedValue;
        ColorBlock newColours = new ColorBlock();
        newColours.disabledColor = comboGradient.Evaluate(normalizedValue);
        newColours.colorMultiplier = 1;
        comboBar.colors = newColours;
        comboText.text = (roundedNormalizedValue).ToString() + "X";
    }
Referenced by Update().
SpawnTimingText()
void GameUI.SpawnTimingText (string score, Color color) private
spawns timing score text above the score.
Parameters
score numeric change in score
color colour of the text
    {
        TextMeshProUGUI text = Instantiate(textPrefab, transform).GetComponent<TextMeshProUGUI>();
        text.text = score;
        text.color = color;
        text.transform.SetAsLastSibling();
        StartCoroutine(FadeoutDestroy(text));
    }
Referenced by CreateTimingText().
Update()
void GameUI.Update () private
    {
        SetComboBarValue(GameManager.instance.combo.multiplier);
    }
Member Data Documentation
comboBar
Slider GameUI.comboBar private
comboGradient
Gradient GameUI.comboGradient private
Referenced by SetComboBarValue().
comboText
TextMeshProUGUI GameUI.comboText private
fadeoutTimer
float GameUI.fadeoutTimer private
Referenced by FadeoutDestroy().
instance
GameUI GameUI.instance static
Referenced by SongScore.AddScore(), Awake(), and Combo.ChangeMultiplier().
scoreText
TextMeshProUGUI GameUI.scoreText private
textPrefab
GameObject GameUI.textPrefab private
Referenced by SpawnTimingText().
The documentation for this class was generated from the following file:
Assets/Scripts/GameUI.cs