KiBoard GDD & Technical Documentation: MoveNotes Class Reference
MoveNotes Class Reference
EditorAction for moving currently selected notes.
Protected Member Functions
override void Down ()
Called on MouseButtonDown()
override void Hold ()
Called on MouseButton() (excludes first frame pressed)
override void Up ()
Called on MouseButtonUp()
Protected Member Functions inherited from EditorAction
virtual void ScrollWheel ()
bool GetMouseRaycast (out RaycastHit2D hit)
Sends raycast from Camera.main to mouse position and assigns the raycasthit2d to hit.
bool CheckDown ()
bool CheckHold ()
bool CheckUp ()
Private Member Functions
void moveNotes (float xDist, float yDist)
handles moving currently selected notes.
void UpdateNoteEvents ()
Updates start/end time and note number after moving notes.
Private Attributes
Vector2 downPos
Vector2 holdpos
List< NoteWrapper > notes = new()
float x
float y
Additional Inherited Members
Public Member Functions inherited from EditorAction
EditorAction SetEditorAction (sbyte mouseNum)
Returns a pre existing editoraction and allows you to set the button used to activate it at the same time.
virtual void HandleInput ()
calls all other input methods (down,hold,up,scrollwheel).
Protected Attributes inherited from EditorAction
sbyte mouseButton
RaycastHit2D hit
Detailed Description
EditorAction for moving currently selected notes.
Member Function Documentation
Down()
override void MoveNotes.Down () protected virtual
Called on MouseButtonDown()
Reimplemented from EditorAction.
    {
        if (CheckDown()) return;
        downPos = hit.point;
        foreach(EditorNote note in SongEditor.instance.selectedNotes)
        {
            notes.Add(new(note));
        }
    }
Hold()
override void MoveNotes.Hold () protected virtual
Called on MouseButton() (excludes first frame pressed)
Reimplemented from EditorAction.
    {
        if (CheckHold()) return;
        if (GetMouseRaycast(out RaycastHit2D holdHit))
        {
            holdpos = holdHit.point;
            moveNotes(downPos.x - holdpos.x, downPos.y - holdpos.y);
        }
    }
moveNotes()
void MoveNotes.moveNotes (float xDist, float yDist) private
handles moving currently selected notes.
Parameters
xDist Distance the mouse has moved on the x axis since button down
yDist Distance the mouse has moved on the y axis since button down
    {
        Debug.Log(xDist + " " + yDist);
        // detect if mouse has moved multiples of 1 unit on the x axis, or vsnap units on the y axis and shift note positions accordingly.
        foreach(NoteWrapper note in notes)
        {
            x = Mathf.RoundToInt(-xDist);
            y = Utility.RoundToFraction(-yDist, SongEditor.instance.vSnap);
            Vector3 posChange = (Vector3)note.initialPosition + new Vector3(x,y,0);
            note.editorNote.transform.position = new Vector3(Mathf.Clamp(posChange.x, 0, 87), Mathf.Clamp(posChange.y, 0, Mathf.Infinity), posChange.z);
        }
    }
Referenced by Hold().
Up()
override void MoveNotes.Up () protected virtual
Called on MouseButtonUp()
Reimplemented from EditorAction.
    {
        if (CheckUp()) return;
        UpdateNoteEvents();
        notes.Clear();
    }
UpdateNoteEvents()
void MoveNotes.UpdateNoteEvents () private
Updates start/end time and note number after moving notes.
    {
        foreach (NoteWrapper note in notes)
        {
            note.editorNote.UpdateNoteEvent();
            note.editorNote.UpdateNoteNumber();
        }
    }
Referenced by Up().
Member Data Documentation
downPos
Vector2 MoveNotes.downPos private
Referenced by Down(), and Hold().
holdpos
Vector2 MoveNotes.holdpos private
Referenced by Hold().
notes
List<NoteWrapper> MoveNotes.notes = new() private
Referenced by Down(), moveNotes(), Up(), and UpdateNoteEvents().
x
float MoveNotes.x private
Referenced by moveNotes().
y
float MoveNotes.y private
Referenced by moveNotes().
The documentation for this class was generated from the following file:
Assets/Scripts/SongEditor.cs