KiBoard GDD & Technical Documentation: EditorNote Class Reference
EditorNote Class Reference
Represents a note in the editor with associated event information.
Public Member Functions
void UpdateNoteEvent (int noteNumber, float startTime, float endTime)
Updates the note event information. start and end time are based off of height of mouse when adding a note.
void UpdateNoteEvent (float startTime, float endTime)
Update only start and end time of note event.
void UpdateNoteEvent ()
Set start and end time of notes based on current y position and scale. /summary>
void UpdateNoteNumber ()
void SetColour (Color newColour)
Sets the highlight color of the note.
void SetNotePosition (float mouseHeight)
Sets the position of the note based on mouse height and key origin X.
Vector2 GridSnapNote (Vector2 input, float increment=0.204545f)
Snaps the note position to the grid based on the specified increment.
Public Attributes
NoteEventInfo noteEvent
Private Member Functions
void Start ()
Private Attributes
SpriteRenderer sprite
Static Private Attributes
const float noteTimingOffset = 1 / 30f
Detailed Description
Represents a note in the editor with associated event information.
Member Function Documentation
GridSnapNote()
Vector2 EditorNote.GridSnapNote (Vector2 input, float increment = 0::204545f)
Snaps the note position to the grid based on the specified increment.
Parameters
input The input position to snap.
increment The grid snap increment.
Returns
The snapped position.
    {
        float x = Mathf.Round(input.x / increment) * increment;
        return new Vector2(x, input.y);
    }
SetColour()
void EditorNote.SetColour (Color newColour)
Sets the highlight color of the note.
Parameters
newColour The new highlight color.
    {
        sprite.color = newColour;
    }
Referenced by SongEditor.ClearSelectedNotes().
SetNotePosition()
void EditorNote.SetNotePosition (float mouseHeight)
Sets the position of the note based on mouse height and key origin X.
Parameters
mouseHeight The height of the mouse.
keyOriginX The origin X position of the key.
    {
        float height = mouseHeight >= Mathf.NegativeInfinity ? mouseHeight : 1;
        //Vector2 gridSnap = GridSnapNote();
        transform.position = new Vector2(noteEvent.noteNumber, height);
    }
Start()
void EditorNote.Start () private
    {
        sprite = GetComponent<SpriteRenderer>();
    }
UpdateNoteEvent() [1/3]
void EditorNote.UpdateNoteEvent ()
Set start and end time of notes based on current y position and scale. /summary>
    {
        float halfScale = transform.localScale.y / 2;
        noteEvent.startTime = transform.position.y - halfScale - noteTimingOffset;
        noteEvent.endTime = transform.position.y + halfScale - noteTimingOffset;
    }
UpdateNoteEvent() [2/3]
void EditorNote.UpdateNoteEvent (float startTime, float endTime)
Update only start and end time of note event.
Parameters
startTime
endTime
    {
        noteEvent.startTime = (startTime / 15) - noteTimingOffset;
        noteEvent.endTime = (endTime / 15 )- noteTimingOffset;
    }
UpdateNoteEvent() [3/3]
void EditorNote.UpdateNoteEvent (int noteNumber, float startTime, float endTime)
Updates the note event information. start and end time are based off of height of mouse when adding a note.
Parameters
noteNumber The note number.
startTime The start time of the note event.
endTime The end time of the note event.
    {
        noteEvent.startTime = (startTime / 15) -noteTimingOffset;
        noteEvent.endTime = (endTime / 15) - noteTimingOffset;
        noteEvent.noteNumber = noteNumber;
    }
Referenced by ScaleNotes.ScaleNote(), and MoveNotes.UpdateNoteEvents().
UpdateNoteNumber()
void EditorNote.UpdateNoteNumber ()
    {
        noteEvent.noteNumber = Mathf.RoundToInt(transform.position.x);
    }
Referenced by MoveNotes.UpdateNoteEvents().
Member Data Documentation
noteEvent
NoteEventInfo EditorNote.noteEvent
Referenced by SetNotePosition().
noteTimingOffset
const float EditorNote.noteTimingOffset = 1 / 30f static private
Referenced by UpdateNoteEvent(), UpdateNoteEvent(), and UpdateNoteEvent().
sprite
SpriteRenderer EditorNote.sprite private
Referenced by Start().
The documentation for this class was generated from the following file:
Assets/Scripts/EditorNote.cs