KiBoard GDD & Technical Documentation: KiboardDebug Class Reference
KiboardDebug Class Reference
Public Member Functions
void OnEnable ()
void VolumeOverride (bool enabled)
Override the volume of all music played.
Static Public Member Functions
static void ShowDebugMenu ()
show the debug canvas.
static void HideDebugMenu ()
hide the debug canvas.
Static Public Attributes
static KiboardDebug instance
static bool overideVolume = false
Is game currently overriding the volume.
static float overideVolumeValue
Volume value at which to override.
Properties
static bool isMidiConnected [get]
Returns true if any midi device is detected.
Private Member Functions
static int midiInGetNumDevs ()
void Awake ()
void Update ()
void CheckOpenMenu ()
check if the open/close menu hotkey is set.
void OnDisable ()
IEnumerator MonitorMidiDevices ()
begin checking if there is a connected midi device.
IEnumerator CalculateFPS ()
begin calculating Fps.
Private Attributes
Toggle midiConnectedToggle
Text fpsText
InputField volumeOverrideIF
GameObject parent
Static Private Attributes
static Canvas debugCanvas
canvas containing Debug UI
Member Function Documentation
Awake()
void KiboardDebug.Awake () private
    {
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(parent);
            debugCanvas = GetComponent<Canvas>();
        }
        else { Destroy(this); }
    }
CalculateFPS()
IEnumerator KiboardDebug.CalculateFPS () private
begin calculating Fps.
Returns
    {
        while (true)
        {
            yield return new WaitForSeconds(0.1f);
            try { fpsText.text = $"FPS:  {Mathf.Round(10 / Time.deltaTime )/10}"; } // calculate fps and assign to text.
            catch { Debug.LogWarning("Assigning Fps to Debug menu's fpsText encountered an error."); yield break; }
        }
    }
Referenced by OnEnable().
CheckOpenMenu()
void KiboardDebug.CheckOpenMenu () private
check if the open/close menu hotkey is set.
    {
        if (Input.GetKey(KeyCode.LeftAlt)  && Input.GetKeyDown(KeyCode.F1))
        {
            if (debugCanvas.enabled) { HideDebugMenu(); }
            else { ShowDebugMenu(); }
        }
    }
Referenced by Update().
HideDebugMenu()
static void KiboardDebug.HideDebugMenu () static
hide the debug canvas.
    {
        debugCanvas.enabled = false;
    }
Referenced by CheckOpenMenu().
midiInGetNumDevs()
static int KiboardDebug.midiInGetNumDevs () private
MonitorMidiDevices()
IEnumerator KiboardDebug.MonitorMidiDevices () private
begin checking if there is a connected midi device.
Returns
    {
        while (true)
        {
            yield return new WaitForSeconds(0.1f);
            try { midiConnectedToggle.isOn = isMidiConnected; }
            catch { Debug.LogWarning("MidiConnectedToggle was null"); yield break; }
        }
    }
Referenced by OnEnable().
OnDisable()
void KiboardDebug.OnDisable () private
    {
        StopAllCoroutines();
    }
OnEnable()
void KiboardDebug.OnEnable ()
    {
        StartCoroutine(CalculateFPS());
        StartCoroutine(MonitorMidiDevices());
    }
ShowDebugMenu()
static void KiboardDebug.ShowDebugMenu () static
show the debug canvas.
    {
        debugCanvas.enabled = true;
    }
Referenced by CheckOpenMenu().
Update()
void KiboardDebug.Update () private
    {
        CheckOpenMenu();
    }
VolumeOverride()
void KiboardDebug.VolumeOverride (bool enabled)
Override the volume of all music played.
Parameters
enabled is the volume override enabled?
    {
        if (enabled)
        {
            if (!int.TryParse(volumeOverrideIF.text, out int newValue))
            {
                Debug.LogWarning("Error Parsing Volume Override Value");
            }
            else
            {
                MP3Handler.instance.SetVolume( PlayerSettings.musicVolume = Math.Clamp(newValue, 0, 100) );
                overideVolume = true;
            }
        }
        else
        {
            overideVolume = false;
        }
    }
Member Data Documentation
debugCanvas
Canvas KiboardDebug.debugCanvas static private
canvas containing Debug UI
Referenced by Awake(), and CheckOpenMenu().
fpsText
Text KiboardDebug.fpsText private
instance
KiboardDebug KiboardDebug.instance static
Referenced by Awake().
midiConnectedToggle
Toggle KiboardDebug.midiConnectedToggle private
overideVolume
bool KiboardDebug.overideVolume = false static
Is game currently overriding the volume.
Referenced by VolumeOverride().
overideVolumeValue
float KiboardDebug.overideVolumeValue static
Volume value at which to override.
parent
GameObject KiboardDebug.parent private
Referenced by Awake().
volumeOverrideIF
InputField KiboardDebug.volumeOverrideIF private
Referenced by VolumeOverride().
Property Documentation
isMidiConnected
bool KiboardDebug.isMidiConnected static get
Returns true if any midi device is detected.
    {
        get
        {
            return midiInGetNumDevs() > 0;
        }
    }
Referenced by MidiInput.LoadSongFromCurrentSettings(), GameSettingsMenu.MonitorMidiConnections(), and MonitorMidiDevices().
The documentation for this class was generated from the following file:
Assets/Scripts/KiboardDebug.cs