KiBoard GDD & Technical Documentation: Replay Class Reference
Replay Class Reference
Static Public Member Functions
static void StartReplayCapture ()
Clears current replay data, Checks if the selected song is a .replay file and assigns isPlaying Replay, then assigns a BPM to the replay.
static void UpdateReplay (int noteNum, float time)
Adds player input note to the replay data being stored.
static void ClearReplay ()
resets replayNoteData to empty values.
Public Attributes
NoteEventDataWrapper replayNoteData
Stores all player input notes to later be saved as a .replay file.
Static Public Attributes
static Replay instance
singleton reference.
static bool isPlayingReplay = false
Is the currently playing song a .replay file?
static bool recordReplay = false
Should player input be recorded for a .replay file to be made?
Private Member Functions
void Awake ()
Member Function Documentation
Awake()
void Replay.Awake () private
    {
        if(instance == null)
        {
            instance = this;
        }
        else { Destroy(this); }
    }
ClearReplay()
static void Replay.ClearReplay () static
resets replayNoteData to empty values.
    {
        instance.replayNoteData.Reset();
    }
Referenced by StartReplayCapture().
StartReplayCapture()
static void Replay.StartReplayCapture () static
Clears current replay data, Checks if the selected song is a .replay file and assigns isPlaying Replay, then assigns a BPM to the replay.
    {
        ClearReplay();
        if (Path.GetExtension(GameSettings.currentSongPath).Equals(".replay")) { isPlayingReplay = true; }
        instance.replayNoteData.BPM = GameSettings.bpm;
    }
Referenced by GameManager.PrepareNotes().
UpdateReplay()
static void Replay.UpdateReplay (int noteNum, float time) static
Adds player input note to the replay data being stored.
Parameters
noteNum number of the note pressed (0 - 87)
time what songTime the note was pressed.
    {
        if (isPlayingReplay|| !recordReplay||time <0) { return; }
        // Check if the note exists with endTime as Mathf.NegativeInfinity
        var existingNote = instance.replayNoteData.NoteEvents.Find(note => note.noteNumber == noteNum && note.endTime == Mathf.NegativeInfinity);
        if (existingNote != null)
        {
            // If the note exists, update its endTime
            existingNote.endTime = time;
        }
        else
        {
            // If the note doesn't exist, add a new note with endTime as Mathf.NegativeInfinity
            instance.replayNoteData.AddNewNote(noteNum, time, Mathf.NegativeInfinity);
        }
    }
Referenced by MidiInput.NoteOff(), and MidiInput.NoteOn().
Member Data Documentation
instance
Replay Replay.instance static
singleton reference.
Referenced by Awake(), ClearReplay(), GameManager.OnSongEnd(), and UpdateReplay().
isPlayingReplay
bool Replay.isPlayingReplay = false static
Is the currently playing song a .replay file?
Referenced by GameManager.OnSongEnd(), StartReplayCapture(), and UpdateReplay().
recordReplay
bool Replay.recordReplay = false static
Should player input be recorded for a .replay file to be made?
Referenced by UpdateReplay().
replayNoteData
NoteEventDataWrapper Replay.replayNoteData
Stores all player input notes to later be saved as a .replay file.
The documentation for this class was generated from the following file:
Assets/Scripts/Replay.cs