KiBoard GDD & Technical Documentation: SpawnPiano Class Reference
SpawnPiano Class Reference
Public Member Functions
int GetIndexOfSpriteRenderer (SpriteRenderer sr)
gets the index of a specific keys sprite renderer.
Color GetDefaultKeyColour (int i)
gets default colour for a key based on key number.
void ClearAllKeyColours ()
resets colours of all keys on the keyboard.
void UpdateKeyColours (int noteNumber, bool enabled, string timingScore="")
Updates the colours of keys when notes are pressed based off of the timing score.
void SpawnKeyParticle (int keyNum, string score="")
spawn particle effect at pressed key.
Static Public Member Functions
static Color GetKeyColour (int keyNum, string timingScore="")
Get colour of a key based off of timing score.
static Color GetKeyColour (int keyNum, bool isKeyEnabled, string timingScore="")
Get colour of a key based off of timing score taking in to account notes being released.
Static Public Attributes
static SpawnPiano instance
Private Member Functions
void Awake ()
Static Private Member Functions
static bool CheckBlackNote (int i)
is the note at index I a black note?
Private Attributes
GameObject pianoWhiteTilePrefab
GameObject keyParticlePrefab
SpriteRenderer[] spriterenderers = new SpriteRenderer[88]
array of sprites for each key of the piano.
Color lane1
Lane colour 1.
Color lane2
lane colour 2.
Static Private Attributes
static Color enabledColour = new Color(255, 0, 0, 128)
colour when incorrectly pressed/timed.
static Color perfectColour = new Color(255, 0, 195, 128)
colour when perfectly timed
static Color goodColour = new Color(0.15f, 1, .5f, 128)
colour when pressed with good timing.
static Color okayColour = new Color(0, 9, 255, 128)
colour when pressed with okay timing.
Member Function Documentation
Awake()
void SpawnPiano.Awake () private
    {
        if (instance == null) { instance = this; }
        else { Destroy(instance.gameObject); }
    }
CheckBlackNote()
static bool SpawnPiano.CheckBlackNote (int i) static private
is the note at index I a black note?
    {
        int value = i % 12;
        if(GameSettings.usePiano) return value == 2 || value == 5 || value == 7 || value == 10 || (value == 0 && i != 0);
        return value == 0 || value == 2 ||value == 5 || value == 7 || value == 10 ;
    }
Referenced by GetDefaultKeyColour(), and GetKeyColour().
ClearAllKeyColours()
void SpawnPiano.ClearAllKeyColours ()
resets colours of all keys on the keyboard.
    {
        for (int i = 0; i < 88; i++)
        {
            spriterenderers[i].color = GetDefaultKeyColour(i);
        }
    }
GetDefaultKeyColour()
Color SpawnPiano.GetDefaultKeyColour (int i)
gets default colour for a key based on key number.
Parameters
i
Returns
    {
        return CheckBlackNote(i + 1) ? Color.black : Color.white;
    }
Referenced by ClearAllKeyColours().
GetIndexOfSpriteRenderer()
int SpawnPiano.GetIndexOfSpriteRenderer (SpriteRenderer sr)
gets the index of a specific keys sprite renderer.
Parameters
sr
Returns
    {
        return Array.IndexOf(spriterenderers, sr);
    }
GetKeyColour() [1/2]
static Color SpawnPiano.GetKeyColour (int keyNum, bool isKeyEnabled, string timingScore = "") static
Get colour of a key based off of timing score taking in to account notes being released.
    {
        if (!isKeyEnabled)
        {
            if (CheckBlackNote(keyNum + 1)) { return Color.black; }
            else { return Color.white; }
        }
        switch (timingScore)
        {
            case "Perfect":
                return perfectColour;
            case "Good":
                return goodColour;
            case "Okay":
                return okayColour;
            default:
                return enabledColour;
        }
    }
GetKeyColour() [2/2]
static Color SpawnPiano.GetKeyColour (int keyNum, string timingScore = "") static
Get colour of a key based off of timing score.
    {
        switch (timingScore)
        {
            case "Perfect":
                return perfectColour;
            case "Good":
                return goodColour;
            case "Okay":
                return okayColour;
            default:
                return enabledColour;
        }
    }
Referenced by SpawnKeyParticle(), and UpdateKeyColours().
SpawnKeyParticle()
void SpawnPiano.SpawnKeyParticle (int keyNum, string score = "")
spawn particle effect at pressed key.
Parameters
keyNum key number to spawn the particles at.
score timing score used for colouring the particles.
    {
        ParticleSystem particle;
        if (GameSettings.usePiano) { particle = Instantiate(keyParticlePrefab, spriterenderers[keyNum].transform).GetComponent<ParticleSystem>(); }
        else { particle = Instantiate(keyParticlePrefab, spriterenderers[(keyNum-3 )%12].transform).GetComponent<ParticleSystem>(); }
        particle.transform.position += Vector3.up / 2;
        ParticleSystem.MainModule main = particle.main;
        main.startColor = GetKeyColour(keyNum, score);
        particle.Play();
        Destroy(particle, 5f);
    }
UpdateKeyColours()
void SpawnPiano.UpdateKeyColours (int noteNumber, bool enabled, string timingScore = "")
Updates the colours of keys when notes are pressed based off of the timing score.
Parameters
noteNumber note number of the note pressed.
enabled is the note being enabled or disabled?
timingScore timing score of the note.
    {
        if (GameSettings.usePiano)
        {
            spriterenderers[noteNumber].color = GetKeyColour(noteNumber, enabled, timingScore);
        }
        else
        {
            spriterenderers[(noteNumber-3 )% 12].color = GetKeyColour(noteNumber, enabled, timingScore);
        }
    }
Member Data Documentation
enabledColour
Color SpawnPiano.enabledColour = new Color(255, 0, 0, 128) static private
colour when incorrectly pressed/timed.
Referenced by GetKeyColour(), and GetKeyColour().
goodColour
Color SpawnPiano.goodColour = new Color(0.15f, 1, .5f, 128) static private
colour when pressed with good timing.
Referenced by GetKeyColour(), and GetKeyColour().
instance
SpawnPiano SpawnPiano.instance static
Referenced by SongNoteEditor.AddNote(), Awake(), MidiInput.NoteOff(), MidiInput.NoteOn(), MidiInput.OnNoteSuccess(), and MidiInput.PedalStateChanged().
keyParticlePrefab
GameObject SpawnPiano.keyParticlePrefab private
Referenced by SpawnKeyParticle().
lane1
Color SpawnPiano.lane1 private
Lane colour 1.
lane2
Color SpawnPiano.lane2 private
lane colour 2.
okayColour
Color SpawnPiano.okayColour = new Color(0, 9, 255, 128) static private
colour when pressed with okay timing.
Referenced by GetKeyColour(), and GetKeyColour().
perfectColour
Color SpawnPiano.perfectColour = new Color(255, 0, 195, 128) static private
colour when perfectly timed
Referenced by GetKeyColour(), and GetKeyColour().
pianoWhiteTilePrefab
GameObject SpawnPiano.pianoWhiteTilePrefab private
spriterenderers
SpriteRenderer [] SpawnPiano.spriterenderers = new SpriteRenderer[88] private
array of sprites for each key of the piano.
Referenced by ClearAllKeyColours(), GetIndexOfSpriteRenderer(), SpawnKeyParticle(), and UpdateKeyColours().
The documentation for this class was generated from the following file:
Assets/Scripts/SpawnPiano.cs