KiBoard GDD & Technical Documentation: TriMouseButton Class Reference
TriMouseButton Class Reference
SongEditor custom Button Ui script to allow for middle and right mouse clicks on buttons.
Public Member Functions
override void OnPointerClick (PointerEventData eventData)
void LeftClick ()
void MiddleClick ()
void RightClick ()
void ResetColour ()
Reset colour block to White.
Public Attributes
UnityEvent onMiddleClick
UnityEvent onRightClick
sbyte mouseButton
what number mouse button this button's action is bound to currently.
Protected Member Functions
override void Awake ()
Private Member Functions
void SetAction (ref EditorAction action, sbyte mouseButton)
Assigns an EditorAction based on gameObject.name to the coresponding mouse button this script was activated with.
ColorBlock SetInactiveColour (Color newColour)
Creates and returns a color block with all values set to NewColour.
Detailed Description
SongEditor custom Button Ui script to allow for middle and right mouse clicks on buttons.
Member Function Documentation
Awake()
override void TriMouseButton.Awake () protected
    {
        onMiddleClick.AddListener(MiddleClick);
        onRightClick.AddListener(RightClick);
    }
LeftClick()
void TriMouseButton.LeftClick ()
    {
        SetAction(ref SongEditor.instance.leftAction, mouseButton = 0);
    }
MiddleClick()
void TriMouseButton.MiddleClick ()
    {
        SetAction(ref SongEditor.instance.middleAction, mouseButton =2);
    }
Referenced by Awake().
OnPointerClick()
override void TriMouseButton.OnPointerClick (PointerEventData eventData)
    {
        base.OnPointerClick(eventData);
        if (eventData.button == PointerEventData.InputButton.Middle)
        {
            onMiddleClick?.Invoke();
        }
        else if (eventData.button == PointerEventData.InputButton.Right)
        {
            onRightClick?.Invoke();
        }
    }
ResetColour()
void TriMouseButton.ResetColour ()
Reset colour block to White.
    {
        colors = SetInactiveColour(Color.white);
    }
RightClick()
void TriMouseButton.RightClick ()
    {
        SetAction(ref SongEditor.instance.rightAction, mouseButton = 1);
    }
Referenced by Awake().
SetAction()
void TriMouseButton.SetAction (ref EditorAction action, sbyte mouseButton) private
Assigns an EditorAction based on gameObject.name to the coresponding mouse button this script was activated with.
Parameters
action Action to be assigned to
mouseButton mouse button number to assign action to.
    {
        if (action != null) // if an action was already selected:
        {
            action.Reset();// clear any variables that specific action may use
            var tmb = SongEditor.instance.triMouseButtons.Where(button => button.mouseButton == mouseButton); // get all trimousebuttons with matching button number.
            foreach(var b in tmb) { b.ResetColour(); } // reset their colours.
        }
        action = SongEditor.instance.InitializeAction(gameObject.name, mouseButton); // initialize and assign new editor action.
        colors = SetInactiveColour(SongEditor.instance.mouseButtonColours[mouseButton]); // on selection, change colour of the button to corespond with which mouse button it is now bound to.
    }
Referenced by LeftClick(), MiddleClick(), and RightClick().
SetInactiveColour()
ColorBlock TriMouseButton.SetInactiveColour (Color newColour) private
Creates and returns a color block with all values set to NewColour.
Parameters
newColour new colour to fill the colorblock.
Returns
    {
        return new ColorBlock()
        {
            highlightedColor = newColour,
            normalColor = newColour,
            pressedColor = newColour,
            selectedColor = newColour,
            disabledColor = newColour,
            colorMultiplier = 1
        };
    }
Referenced by ResetColour(), and SetAction().
Member Data Documentation
mouseButton
sbyte TriMouseButton.mouseButton
what number mouse button this button's action is bound to currently.
Referenced by LeftClick(), MiddleClick(), RightClick(), and SetAction().
onMiddleClick
UnityEvent TriMouseButton.onMiddleClick
Referenced by Awake(), and OnPointerClick().
onRightClick
UnityEvent TriMouseButton.onRightClick
Referenced by Awake(), and OnPointerClick().
The documentation for this class was generated from the following file:
Assets/Scripts/TriMouseButton.cs