KiBoard GDD & Technical Documentation: SongNoteEditor Class Reference
SongNoteEditor Class Reference
Public Member Functions
void OnRightMouseDown ()
void OnRightMouseHold ()
void OnLeftMouseDown ()
void OnLeftMouseHold ()
void OnLeftMouseUp ()
void ScaleNote ()
float ConvertYPositionToSongTime (Vector2 position)
Vector2 ConvertNoteEventToNotePosition (NoteEventInfo noteEvent)
void RescaleNotesFromBPM ()
Static Public Member Functions
static Vector2 GridSnapNote (Vector2 input, float increment=0.204545f)
Public Attributes
HashSet< EditorNoteWrapper > selectedNotes = new HashSet<EditorNoteWrapper>()
float selectCount
Private Member Functions
void Update ()
void AddNote ()
void SubtractNote ()
void SelectNote ()
void DeselectNote ()
void DeselectAllNotes ()
void DragNote ()
void CopySelection ()
void PasteSelection ()
void UpdateStartEndTimes (NoteEventInfo noteEvent, float snappedYPos)
Vector2 GetOffsetFromTransform (Vector2 point, Transform referenceTransform)
bool IsTransformInSelectedNotes (Transform targetTransform)
void UpdateSelectedNoteOffsets ()
Private Attributes
Vector2 mousePosition1
Vector2 mousePosition2
LayerMask groupSelectLayerMask
bool isGroupSelecting
bool isDragging
bool isScaling
RaycastHit2D hit
Member Function Documentation
AddNote()
void SongNoteEditor.AddNote () private
    {
        if (hit.collider.CompareTag("KeyLane"))
        {
            DeselectAllNotes();
            int noteNumber = 1 + SpawnPiano.instance.GetIndexOfSpriteRenderer(hit.transform.parent.GetComponent<SpriteRenderer>());
            //SongEditor.instance.CreateNote(noteNumber, mousePosition1.y, mousePosition1.y + 0.5f, mousePosition1.y);
            RescaleNotesFromBPM();
        }
    }
Referenced by OnLeftMouseDown().
ConvertNoteEventToNotePosition()
Vector2 SongNoteEditor.ConvertNoteEventToNotePosition (NoteEventInfo noteEvent)
    {
        var result = new Vector2(noteEvent.noteNumber * 1, noteEvent.startTime * (GameSettings.bpm / 60));
        return result;
    }
ConvertYPositionToSongTime()
float SongNoteEditor.ConvertYPositionToSongTime (Vector2 position)
    {
        // 1 unit = 1 "beat" or bar on the UI
        return position.y / (GameSettings.bpm / 60);
        // y position / bpm /60 so it is bpS
    }
CopySelection()
void SongNoteEditor.CopySelection () private
    {
    }
DeselectAllNotes()
void SongNoteEditor.DeselectAllNotes () private
    {
        foreach (EditorNoteWrapper note in selectedNotes)
        {
            note.noteTransform.GetComponent<EditorNote>().ResetHighlightColour();
        }
        selectedNotes.Clear();
    }
Referenced by AddNote(), and SubtractNote().
DeselectNote()
void SongNoteEditor.DeselectNote () private
    {
        if (hit.collider.CompareTag("EditorNote"))
        {
            HashSet<EditorNoteWrapper> noteStorage = new();
            foreach (EditorNoteWrapper note in selectedNotes)
            {
                if (note.noteTransform == hit.transform) { note.noteTransform.GetComponent<EditorNote>().ResetHighlightColour(); }
                else { noteStorage.Add(note); }
            }
            selectedNotes.Clear();
            selectedNotes = noteStorage;
        }
    }
Referenced by OnLeftMouseDown(), OnLeftMouseHold(), OnRightMouseDown(), and OnRightMouseHold().
DragNote()
void SongNoteEditor.DragNote () private
    {
        if (hit.collider.CompareTag("EditorNote") && !isDragging)
        {
            isDragging = true;
            UpdateSelectedNoteOffsets();
            if (IsTransformInSelectedNotes(hit.transform))
            {
                var temp = new EditorNoteWrapper(hit.transform, GetOffsetFromTransform(hit.point, hit.transform));
                selectedNotes.Add(temp);
                temp.noteTransform.GetComponent<EditorNote>().SetHighlightColour(Color.red);
            }
        }
        if (selectedNotes.Count > 0 && isDragging && !Input.GetKeyDown(KeyCode.LeftShift))
        {
            Vector2 mousePosition2 = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            foreach (EditorNoteWrapper dragNote in selectedNotes)
            {
                // Calculate the snapped position
                Vector2 snappedPosition = GridSnapNote(mousePosition2 + dragNote.initialOffset);
                // Update the note's position
                dragNote.noteTransform.position = new Vector2(snappedPosition.x - 0.05f, snappedPosition.y);
                UpdateStartEndTimes(dragNote.noteTransform.GetComponent<EditorNote>().noteEvent, snappedPosition.y);
                // idk why i need to realign it with a -0.25f shift but whatever, it works
            }
        }
    }
Referenced by OnLeftMouseHold().
GetOffsetFromTransform()
Vector2 SongNoteEditor.GetOffsetFromTransform (Vector2 point, Transform referenceTransform) private
    {
        return (Vector2)referenceTransform.position - point;
    }
Referenced by DragNote(), SelectNote(), and UpdateSelectedNoteOffsets().
GridSnapNote()
static Vector2 SongNoteEditor.GridSnapNote (Vector2 input, float increment = 0::204545f) static
    {
        float x = Mathf.Round(input.x / increment) * increment;
        return new Vector2(x-0.095f, input.y);
    }
Referenced by DragNote().
IsTransformInSelectedNotes()
bool SongNoteEditor.IsTransformInSelectedNotes (Transform targetTransform) private
    {
        foreach (var noteWrapper in selectedNotes)
        {
            if (noteWrapper.noteTransform == targetTransform)
            {
                return true; // Found a match
            }
        }
        return false; // No match found
    }
Referenced by DragNote().
OnLeftMouseDown()
void SongNoteEditor.OnLeftMouseDown ()
    {
        if (!Input.GetMouseButtonDown(0)) return; // only run if LMB down.
        var mousePositionWorld = Camera.main.ScreenToWorldPoint(Input.mousePosition); // convert mouse position in screen space to world space.
        hit = Physics2D.Raycast(mousePositionWorld, Vector2.zero);// shoot ray from mouse position.
        if (hit) { mousePosition1 = hit.point; Debug.Log(hit.collider.name); } // set mousepos1 if hit, otherwise return.
        else { Debug.Log("NullHit"); return; }
        UpdateSelectedNoteOffsets();
        if (Input.GetKey(KeyCode.LeftShift))
        {
            SelectNote();
        }
        else if (Input.GetKey(KeyCode.LeftControl))
        {
            DeselectNote();
        }
        else if (!isDragging)
        {
            AddNote();
        }
    }
Referenced by Update().
OnLeftMouseHold()
void SongNoteEditor.OnLeftMouseHold ()
    {
        if (!Input.GetMouseButton(0)) return; // only run if LMB down.
        var mousePositionWorld = Camera.main.ScreenToWorldPoint(Input.mousePosition); // convert mouse position in screen space to world space.
        hit = Physics2D.Raycast(mousePositionWorld, Vector2.zero);// shoot ray from mouse position.
        if (hit) { mousePosition2 = hit.point; } // set mousepos1 if hit, otherwise return.
        else { Debug.Log("NullHit"); return; }
        if (Input.GetKey(KeyCode.LeftShift))
        {
            SelectNote();
        }
        else if (Input.GetKey(KeyCode.LeftControl))
        {
            DeselectNote();
        }
        else
        {
            DragNote();
        }
    }
Referenced by Update().
OnLeftMouseUp()
void SongNoteEditor.OnLeftMouseUp ()
    {
        if (!Input.GetMouseButtonUp(0)) return;
        foreach (GameObject note in SongEditor.instance.noteObjects)
        {
            UpdateStartEndTimes(note.GetComponent<EditorNote>().noteEvent,note.transform.position.y );
        }
        isDragging = false;
    }
Referenced by Update().
OnRightMouseDown()
void SongNoteEditor.OnRightMouseDown ()
    {
        if (!Input.GetMouseButtonDown(1)) return; // only run if LMB down.
        var mousePositionWorld = Camera.main.ScreenToWorldPoint(Input.mousePosition); // convert mouse position in screen space to world space.
        hit = Physics2D.Raycast(mousePositionWorld, Vector2.zero);// shoot ray from mouse position.
        if (hit) { mousePosition1 = hit.point; } // set mousepos1 if hit, otherwise return.
        else { Debug.Log("NullHit"); return; }
        UpdateSelectedNoteOffsets();
        if (Input.GetKey(KeyCode.LeftShift))
        {
            SelectNote();
        }
        else if (Input.GetKey(KeyCode.LeftControl))
        {
            DeselectNote();
        }
        else { SubtractNote(); }
    }
Referenced by Update().
OnRightMouseHold()
void SongNoteEditor.OnRightMouseHold ()
    {
        if (!Input.GetMouseButton(1)) return; // only run if LMB down.
        var mousePositionWorld = Camera.main.ScreenToWorldPoint(Input.mousePosition); // convert mouse position in screen space to world space.
        hit = Physics2D.Raycast(mousePositionWorld, Vector2.zero);// shoot ray from mouse position.
        if (hit) { mousePosition1 = hit.point; } // set mousepos1 if hit, otherwise return.
        else { Debug.Log("NullHit"); return; }
        UpdateSelectedNoteOffsets();
        if (Input.GetKey(KeyCode.LeftShift))
        {
            SelectNote();
        }
        else if (Input.GetKey(KeyCode.LeftControl))
        {
            DeselectNote();
        }
        else { SubtractNote(); }
    }
Referenced by Update().
PasteSelection()
void SongNoteEditor.PasteSelection () private
    {
    }
RescaleNotesFromBPM()
void SongNoteEditor.RescaleNotesFromBPM ()
    {
        float modifiedScale = GameManager.instance.modifiedNoteScale;
        foreach (GameObject g in SongEditor.instance.noteObjects)
        {
            var sr = g.GetComponent<SpriteRenderer>();
            var newSize = new Vector2(sr.size.x, Mathf.Clamp(((
                g.GetComponent<EditorNote>().noteEvent.endTime -
                g.GetComponent<EditorNote>().noteEvent.startTime)), 0.5f, Mathf.Infinity));
            sr.size = newSize;
            sr.GetComponent<EditorNote>().SetShadowSize(newSize.y);
        }
    }
Referenced by AddNote(), and ScaleNote().
ScaleNote()
void SongNoteEditor.ScaleNote ()
    {
        if (selectedNotes.Count > 0 && Input.GetKey(KeyCode.LeftShift))
        {
            var scroll = Input.mouseScrollDelta.y;
            if (scroll != 0)
            {
                foreach (NoteEventInfo noteEvent in SongEditor.FindNoteEventInfo(selectedNotes))
                {
                    if (noteEvent.endTime <= noteEvent.startTime || noteEvent.endTime + Mathf.Sign(scroll) * 0.1f <= noteEvent.startTime)
                    {
                        noteEvent.endTime = noteEvent.startTime + 0.05f;
                    }
                    else
                    {
                        noteEvent.endTime += Mathf.Sign(scroll) * 0.05f;
                    }
                    RescaleNotesFromBPM();
                }
            }
        }
    }
Referenced by Update().
SelectNote()
void SongNoteEditor.SelectNote () private
    {
        if (hit.collider.CompareTag("EditorNote"))
        {
            if (!selectedNotes.Any(note => note.noteTransform == hit.transform))
            {
                var temp = new EditorNoteWrapper(hit.transform, GetOffsetFromTransform(hit.point, hit.transform));
                selectedNotes.Add(temp);
                temp.noteTransform.GetComponent<EditorNote>().SetHighlightColour(Color.red);
            }
        }
    }
Referenced by OnLeftMouseDown(), OnLeftMouseHold(), OnRightMouseDown(), and OnRightMouseHold().
SubtractNote()
void SongNoteEditor.SubtractNote () private
    {
        if (hit.collider.TryGetComponent<EditorNote>(out var noteEvent))
        {
            DeselectAllNotes();
            selectedNotes.RemoveWhere(note => note.noteTransform == noteEvent.transform);
            SongEditor.instance.RemoveNoteEvent(noteEvent, true);
        }
    }
Referenced by OnRightMouseDown(), and OnRightMouseHold().
Update()
void SongNoteEditor.Update () private
    {
        OnLeftMouseDown();
        OnLeftMouseHold();
        OnLeftMouseUp();
        OnRightMouseDown();
        OnRightMouseHold();
        ScaleNote();
    }
UpdateSelectedNoteOffsets()
void SongNoteEditor.UpdateSelectedNoteOffsets () private
    {
        foreach (EditorNoteWrapper dragNote in selectedNotes)
        {
            dragNote.initialOffset = GetOffsetFromTransform(hit.point, dragNote.noteTransform); // assign all offset values for clicking and dragging.
        }
    }
Referenced by DragNote(), OnLeftMouseDown(), OnRightMouseDown(), and OnRightMouseHold().
UpdateStartEndTimes()
void SongNoteEditor.UpdateStartEndTimes (NoteEventInfo noteEvent, float snappedYPos) private
    {
        float duration = noteEvent.GetDuration();
        float newStartTime = snappedYPos - (duration / 2); // ConvertYPositionToSongTime(snappedPosition);
        noteEvent.SetStartEndTime(newStartTime, newStartTime + duration);
    }
Referenced by DragNote(), and OnLeftMouseUp().
Member Data Documentation
groupSelectLayerMask
LayerMask SongNoteEditor.groupSelectLayerMask private
hit
RaycastHit2D SongNoteEditor.hit private
Referenced by AddNote(), DeselectNote(), DragNote(), OnLeftMouseDown(), OnLeftMouseHold(), OnRightMouseDown(), OnRightMouseHold(), SelectNote(), SubtractNote(), and UpdateSelectedNoteOffsets().
isDragging
bool SongNoteEditor.isDragging private
Referenced by DragNote(), OnLeftMouseDown(), and OnLeftMouseUp().
isGroupSelecting
bool SongNoteEditor.isGroupSelecting private
isScaling
bool SongNoteEditor.isScaling private
mousePosition1
Vector2 SongNoteEditor.mousePosition1 private
Referenced by OnLeftMouseDown(), OnRightMouseDown(), and OnRightMouseHold().
mousePosition2
Vector2 SongNoteEditor.mousePosition2 private
Referenced by DragNote(), and OnLeftMouseHold().
selectCount
float SongNoteEditor.selectCount
selectedNotes
HashSet<EditorNoteWrapper> SongNoteEditor.selectedNotes = new HashSet<EditorNoteWrapper>()
Referenced by DeselectAllNotes(), DeselectNote(), DragNote(), IsTransformInSelectedNotes(), ScaleNote(), SelectNote(), SubtractNote(), and UpdateSelectedNoteOffsets().
The documentation for this class was generated from the following file:
Assets/Scripts/SongNoteEditor.cs