KiBoard GDD & Technical Documentation: SongEditor Class Reference
SongEditor Class Reference
Manages the song editor functionality.
Public Member Functions
void CreateNote (RaycastHit2D hit)
Takes a raycast hit and spawns an editorNorePrefab.
void RemoveNote (EditorNote note)
removes an editornote from the editorNotes list and then destroys the gameObject it is attatched to.
void InitializePianoRoll ()
Spawns the piano roll.
Vector2 SnapNote (Vector2 pos)
Rounds a vector2's values to the nearest fraction of 1/Vsnap.
float ScaleToBeat (float num)
void SelectButton (Button button)
Called in the editor ui buttons. When clicked it will grey out a selected button and un grey out the previously selected one.
EditorAction InitializeAction (string actionName, sbyte mouseNumber)
Public Attributes
Dictionary< int, GameObject > keyLanes = new()
Dictionary of intiger X positions and key lane objects for easy detection and positioning.
float heightMultiplier = 15
every 15 units in unity is one beat.
float vSnap = 0
how many subdivisions for vertical note snapping.
bool scaleNoteToVSnap
should new notes automatically scale to the size indicated by vSnap.
EditorAction leftAction
EditorActions for the left, middle and right mouse buttons respectively.
Can be bound by calling InitializeAction(string, sbyte) with a string corresponding to the name of the editor action, and a sByte containing the number mouse button.
EditorAction middleAction
EditorAction rightAction
Static Public Attributes
static SongEditor instance
Private Member Functions
void Awake ()
void Start ()
void Update ()
Private Attributes
Transform noteHolder
parent of all notes spawned by player.
GameObject editorNotePrefab
Camera cam
GameObject keyPrefab
Color keyLaneColour1
Color keyLaneColour2
Vector3 keyLaneScale = new Vector3(1, 20, 1)
size of key lanes
Vector3 baseKeyScale = new Vector3(.8f, 5, 1)
size of piano keys.
Vector2 defaultNoteScale = new(1, 1)
Color noteColour
List< EditorNote > editorNotes = new()
list of editornotes.
AddNote addNote = new()
RemoveNotes removeNotes = new()
Button currentlySelectedButton
Detailed Description
Manages the song editor functionality.
Member Function Documentation
Awake()
void SongEditor.Awake () private
    {
        if (instance == null) { instance = this; }
        else { Destroy(this); }
    }
CreateNote()
void SongEditor.CreateNote (RaycastHit2D hit)
Takes a raycast hit and spawns an editorNorePrefab.
Parameters
hit raycast2dhit information.
    {
        Transform note = Instantiate(editorNotePrefab, noteHolder).transform;// create note
        int noteNum = Mathf.RoundToInt(hit.point.x); // round notes position to get the key number.
        float height = hit.point.y;//get height of the note\
        EditorNote editorNote = note.GetComponent<EditorNote>();
        if (scaleNoteToVSnap)
        {
            if (defaultNoteScale.y > vSnap)
            {
                note.localScale = new(defaultNoteScale.y, Utility.RoundToFraction(defaultNoteScale.y, vSnap));
            }
            else
            {
                note.localScale = new(defaultNoteScale.y, ScaleToBeat(vSnap));
            }
        }
        Vector2 snappeedPos = SnapNote(new Vector2(noteNum, height));
        float halfNoteHeight = note.localScale.y / 2;
        snappeedPos.y += halfNoteHeight;
        note.position = snappeedPos; // round the notes position to nearest fraction of a beat.
        editorNote.UpdateNoteEvent(noteNum, snappeedPos.y - 2f - halfNoteHeight, snappeedPos.y - 2f + halfNoteHeight);
        editorNotes.Add(editorNote);
    }
InitializeAction()
EditorAction SongEditor.InitializeAction (string actionName, sbyte mouseNumber)
    {
        switch (actionName.ToLower())
        {
            case "add":
                return addNote.SetEditorAction(mouseNumber);
            case "remove":
                return removeNotes.SetEditorAction(mouseNumber);
            case "select":
                return null;
            default:
                return null;
        }
    }
Referenced by SelectButton().
InitializePianoRoll()
void SongEditor.InitializePianoRoll ()
Spawns the piano roll.
    {
        for (int i = 0; i < 88; i++)
        {
            Transform trans = Instantiate(keyPrefab, transform).transform;
            trans.position = new(i, 0, 0);
            trans.localScale = baseKeyScale;
            trans.GetComponent<SpriteRenderer>().color = GetKeyColour(i);
            Transform lane = Instantiate(keyPrefab, trans).transform;
            lane.GetComponent<SpriteRenderer>().color = i % 2 == 0 ? keyLaneColour1 : keyLaneColour2;
            lane.localScale = keyLaneScale;
            lane.position += new Vector3(0f, (keyLaneScale.y * baseKeyScale.y / 2) - 2.5f, 1f);
            lane.gameObject.tag = "KeyLane";
            keyLanes.Add(i, lane.gameObject);
        }
        Color GetKeyColour(int i)
        {
            int value = i % 12;
            if (value == 0 || value == 2 || value == 3 || value == 5 || value == 7 || value == 9 || value == 11) return Color.white;
            else { return Color.black; }
        }
    }
Referenced by Start().
RemoveNote()
void SongEditor.RemoveNote (EditorNote note)
removes an editornote from the editorNotes list and then destroys the gameObject it is attatched to.
Parameters
note note to be removed.
    {
        editorNotes.Remove(note);
        Destroy(note.gameObject);
    }
ScaleToBeat()
float SongEditor.ScaleToBeat (float num)
    {
        return 15/ num;
    }
Referenced by CreateNote().
SelectButton()
void SongEditor.SelectButton (Button button)
Called in the editor ui buttons. When clicked it will grey out a selected button and un grey out the previously selected one.
Parameters
button
    {
        if(currentlySelectedButton != null)
        {
            currentlySelectedButton.interactable = true;
        }
        button.interactable = false;
        currentlySelectedButton = button;
        leftAction = InitializeAction(button.gameObject.name,0);
        rightAction = InitializeAction("remove", 1);
    }
SnapNote()
Vector2 SongEditor.SnapNote (Vector2 pos)
Rounds a vector2's values to the nearest fraction of 1/Vsnap.
Parameters
pos Vector to snap
Returns
vector with fraction-rounded values.
    {
        if (vSnap <= 0) { return pos; }
        else { return new Vector2(pos.x, Utility.RoundToFraction(pos.y-5f, vSnap) + 2.5f); }
    }
Referenced by CreateNote().
Start()
void SongEditor.Start () private
    {
        cam = Camera.main;
        InitializePianoRoll();
    }
Update()
void SongEditor.Update () private
    {
        leftAction?.HandleInput();
        middleAction?.HandleInput();
        rightAction?.HandleInput();
    }
Member Data Documentation
addNote
AddNote SongEditor.addNote = new() private
Referenced by InitializeAction().
baseKeyScale
Vector3 SongEditor.baseKeyScale = new Vector3(.8f, 5, 1) private
size of piano keys.
Referenced by InitializePianoRoll().
cam
Camera SongEditor.cam private
Referenced by Start().
currentlySelectedButton
Button SongEditor.currentlySelectedButton private
Referenced by SelectButton().
defaultNoteScale
Vector2 SongEditor.defaultNoteScale = new(1, 1) private
Referenced by CreateNote().
editorNotePrefab
GameObject SongEditor.editorNotePrefab private
Referenced by CreateNote().
editorNotes
List<EditorNote> SongEditor.editorNotes = new() private
list of editornotes.
Referenced by CreateNote(), and RemoveNote().
heightMultiplier
float SongEditor.heightMultiplier = 15
every 15 units in unity is one beat.
instance
SongEditor SongEditor.instance static
Referenced by Awake(), BeatNumberGenerator.CreateBeatNumbers(), AddNote.Down(), and RemoveNotes.RemoveNoteIfHit().
keyLaneColour1
Color SongEditor.keyLaneColour1 private
Referenced by InitializePianoRoll().
keyLaneColour2
Color SongEditor.keyLaneColour2 private
Referenced by InitializePianoRoll().
keyLanes
Dictionary<int, GameObject> SongEditor.keyLanes = new()
Dictionary of intiger X positions and key lane objects for easy detection and positioning.
Referenced by InitializePianoRoll().
keyLaneScale
Vector3 SongEditor.keyLaneScale = new Vector3(1, 20, 1) private
size of key lanes
Referenced by InitializePianoRoll().
keyPrefab
GameObject SongEditor.keyPrefab private
Referenced by InitializePianoRoll().
leftAction
EditorAction SongEditor.leftAction
EditorActions for the left, middle and right mouse buttons respectively.
Can be bound by calling InitializeAction(string, sbyte) with a string corresponding to the name of the editor action, and a sByte containing the number mouse button.
Referenced by SelectButton(), and Update().
middleAction
EditorAction SongEditor.middleAction
Referenced by Update().
noteColour
Color SongEditor.noteColour private
noteHolder
Transform SongEditor.noteHolder private
parent of all notes spawned by player.
Referenced by CreateNote().
removeNotes
RemoveNotes SongEditor.removeNotes = new() private
Referenced by InitializeAction().
rightAction
EditorAction SongEditor.rightAction
Referenced by SelectButton(), and Update().
scaleNoteToVSnap
bool SongEditor.scaleNoteToVSnap
should new notes automatically scale to the size indicated by vSnap.
Referenced by CreateNote().
vSnap
float SongEditor.vSnap = 0
how many subdivisions for vertical note snapping.
Referenced by CreateNote(), and SnapNote().
The documentation for this class was generated from the following file:
Assets/Scripts/SongEditor.cs