KiBoard GDD & Technical Documentation: MidiDataHandler Class Reference
MidiDataHandler Class Reference
Static Public Member Functions
static NoteEventDataWrapper GetJSONData (string fileName)
Retrieves stored MIDI data from a JSON file.
static NoteEventDataWrapper SaveNoteEventData (string extension, float bpm, List< NoteEventInfo > dataToSave)
Saves NoteEventInfo data to a JSON file.
static NoteEventDataWrapper SaveNoteEventData (string extension, NoteEventDataWrapper wrapper)
ONLY USE FOR REPLAYS UNLESS MODIFIED.
static NoteEventDataWrapper LoadNoteEventData (string filePath)
Loads NoteEventInfo data from a JSON file.
Static Private Member Functions
static void SaveToFileCompressed (string data, string filePath)
Saves json string "Data" to a compressed json file at "filePath".
static string LoadFromFileCompressed (string filePath)
loads a json string from a compressed json file at "filePath".
Member Function Documentation
GetJSONData()
static NoteEventDataWrapper MidiDataHandler.GetJSONData (string fileName) static
Retrieves stored MIDI data from a JSON file.
Parameters
fileName The name of the JSON file to load.
Returns
The loaded MIDI data as a NoteEventDataWrapper.
    {
        // Load the previously stored data
        // Return the loaded data
        return LoadNoteEventData(fileName);
    }
Referenced by MidiReadFile.GetDataFile().
LoadFromFileCompressed()
static string MidiDataHandler.LoadFromFileCompressed (string filePath) static private
loads a json string from a compressed json file at "filePath".
Parameters
filePath
Returns
decomressed Json String
    {
        using (FileStream fileStream = new FileStream(filePath, FileMode.Open))
        {
            using (GZipStream zipStream = new GZipStream(fileStream, CompressionMode.Decompress))
            {
                using (StreamReader reader = new StreamReader(zipStream))
                {
                    return reader.ReadToEnd();
                }
            }
        }
    }
Referenced by LoadNoteEventData().
LoadNoteEventData()
static NoteEventDataWrapper MidiDataHandler.LoadNoteEventData (string filePath) static
Loads NoteEventInfo data from a JSON file.
Parameters
fileName The name of the JSON file to load.
Returns
The loaded MIDI data as a NoteEventDataWrapper.
    {
        // Check if the file exists
        if (File.Exists(filePath))
        {
            // Read the JSON string from the file
            string json = LoadFromFileCompressed(filePath);
            // Convert the JSON string back to a list of NoteEventInfo
            return JsonUtility.FromJson<NoteEventDataWrapper>(json);
        }
        else
        {
            Debug.LogWarning("Note event data file does not exist.");
            return null;
        }
    }
Referenced by GetJSONData().
SaveNoteEventData() [1/2]
static NoteEventDataWrapper MidiDataHandler.SaveNoteEventData (string extension, float bpm, List< NoteEventInfo > dataToSave) static
Saves NoteEventInfo data to a JSON file.
Parameters
fileName The name of the JSON file to save.
bpm The BPM (Beats Per Minute) of the song.
dataToSave The list of NoteEventInfo to save.
Returns
The wrapper containing BPM and NoteEventInfo.
    {
        if (dataToSave == null) { Debug.LogError("Data Save Error: NoteEventInfo Null"); return null; }
        // Create a wrapper class to hold both BPM and NoteEventInfo
        var wrapper = new NoteEventDataWrapper
        {
            BPM = bpm,
            NoteEvents = dataToSave
        };
        // Convert the wrapper to a JSON string
        string json = JsonUtility.ToJson(wrapper);
        string folderPath = GameSettings.currentFileGroup.FolderPath;
        string fileName = Path.GetFileNameWithoutExtension(GameSettings.currentSongPath);
        // Define the path where you want to save the JSON file
        if (!Directory.Exists(folderPath))
        {
            try { Directory.CreateDirectory(folderPath); } catch { }
        }
        // Write the JSON string to the file
        SaveToFileCompressed(json, folderPath + "/" +fileName+ extension);
        return wrapper;
    }
Referenced by GameManager.OnSongEnd(), MidiReadFile.ReadMidiFile(), and GameManager.RefreshJsonFiles().
SaveNoteEventData() [2/2]
static NoteEventDataWrapper MidiDataHandler.SaveNoteEventData (string extension, NoteEventDataWrapper wrapper) static
ONLY USE FOR REPLAYS UNLESS MODIFIED.
Parameters
extension
wrapper
Returns
    {
        if (wrapper == null) { Debug.LogError("Data Save Error: NoteEventDataWrapper Null"); return null; }
        // Create a wrapper class to hold both BPM and NoteEventInfo
        // Convert the wrapper to a JSON string
        string json = JsonUtility.ToJson(wrapper);
        string folderPath = GameSettings.currentFileGroup.FolderPath;
        string fileName = Path.GetFileNameWithoutExtension(GameSettings.currentSongPath);
        // Define the path where you want to save the JSON file
        if (!Directory.Exists(folderPath))
        {
            Directory.CreateDirectory(folderPath);
        }
        int versionCount = 0;
        while (true)
        {
            if (!File.Exists($"{folderPath}/{fileName}_{versionCount}{extension}"))
            {
                SaveToFileCompressed(json, $"{folderPath}/{fileName}_{versionCount}{extension}");
                return wrapper;
            }
            else
            {
                versionCount++;
            }
        }
        // Write the JSON string to the file
    }
SaveToFileCompressed()
static void MidiDataHandler.SaveToFileCompressed (string data, string filePath) static private
Saves json string "Data" to a compressed json file at "filePath".
Parameters
data
filePath
    {
        using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
        {
            using (GZipStream zipStream = new GZipStream(fileStream, CompressionMode.Compress))
            {
                using (StreamWriter writer = new StreamWriter(zipStream))
                {
                    writer.Write(data);
                }
            }
        }
    }
Referenced by SaveNoteEventData(), and SaveNoteEventData().
The documentation for this class was generated from the following file:
Assets/Scripts/MidiDataHandler.cs