.TH "Assets/Scripts/BeatNumberGenerator.cs" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/Scripts/BeatNumberGenerator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBeatNumberGenerator\fP"
.br
.RI "Generates beat numbers as TextMeshProUGUI objects\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
