.TH "BeatNumberGenerator" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BeatNumberGenerator \- Generates beat numbers as TextMeshProUGUI objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateBeatNumbers\fP ()"
.br
.RI "Instantiates beat number TextMeshProUGUI objects\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBprefab\fP"
.br
.ti -1c
.RI "int \fBquantity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates beat numbers as TextMeshProUGUI objects\&. 
.SH "Member Function Documentation"
.PP 
.SS "void BeatNumberGenerator\&.CreateBeatNumbers ()"

.PP
Instantiates beat number TextMeshProUGUI objects\&. 
.nf
24     {
25         for (int i = \-3; i <= quantity; i++)
26         {
27             Transform trans = Instantiate(prefab, transform)\&.transform;
28             trans\&.position = new Vector2(trans\&.position\&.x, i);
29             trans\&.GetComponent<TextMeshProUGUI>()\&.text = i\&.ToString();
30         }
31     }
.PP
.fi

.PP
Referenced by \fBStart()\fP\&.
.SS "void BeatNumberGenerator\&.Start ()\fR [private]\fP"

.nf
16     {
17         CreateBeatNumbers();
18        
19     }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "GameObject BeatNumberGenerator\&.prefab\fR [private]\fP"

.PP
Referenced by \fBCreateBeatNumbers()\fP\&.
.SS "int BeatNumberGenerator\&.quantity\fR [private]\fP"

.PP
Referenced by \fBCreateBeatNumbers()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
