.TH "Assets/Scripts Directory Reference" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/Scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBeatNumberGenerator\&.cs\fP"
.br
.ti -1c
.RI "file \fBCameraScrollManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBCameraShake\&.cs\fP"
.br
.ti -1c
.RI "file \fBCombo\&.cs\fP"
.br
.ti -1c
.RI "file \fBEditorNote\&.cs\fP"
.br
.ti -1c
.RI "file \fBExit\&.cs\fP"
.br
.ti -1c
.RI "file \fBExtraSongInfoMenu\&.cs\fP"
.br
.ti -1c
.RI "file \fBFallingNote\&.cs\fP"
.br
.ti -1c
.RI "file \fBFileGroup\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameSettingsMenu\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameUI\&.cs\fP"
.br
.ti -1c
.RI "file \fBKiboardDebug\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainMenuLoad\&.cs\fP"
.br
.ti -1c
.RI "file \fBMidiDataHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBMidiInput\&.cs\fP"
.br
.ti -1c
.RI "file \fBMidiReadFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBMP3Handler\&.cs\fP"
.br
.ti -1c
.RI "file \fBNoteEventInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBNoteShadow\&.cs\fP"
.br
.ti -1c
.RI "file \fBReplay\&.cs\fP"
.br
.ti -1c
.RI "file \fBSongNoteEditor\&.cs\fP"
.br
.ti -1c
.RI "file \fBSongScore\&.cs\fP"
.br
.ti -1c
.RI "file \fBSpawnPiano\&.cs\fP"
.br
.in -1c
