.TH "EditorNoteWrapper" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditorNoteWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditorNoteWrapper\fP (Transform transform, Vector2 offset)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBnoteTransform\fP"
.br
.ti -1c
.RI "Vector2 \fBinitialOffset\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EditorNoteWrapper\&.EditorNoteWrapper (Transform transform, Vector2 offset)"

.nf
367     {
368         noteTransform = transform;
369         initialOffset = offset;
370     }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "Vector2 EditorNoteWrapper\&.initialOffset"

.PP
Referenced by \fBSongNoteEditor\&.DragNote()\fP, and \fBEditorNoteWrapper()\fP\&.
.SS "Transform EditorNoteWrapper\&.noteTransform"

.PP
Referenced by \fBSongNoteEditor\&.DeselectNote()\fP, \fBSongNoteEditor\&.DragNote()\fP, \fBEditorNoteWrapper()\fP, and \fBSongNoteEditor\&.UpdateSelectedNoteOffsets()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
