.TH "Exit" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exit
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExitToDesktopButton\fP (TextMeshProUGUI text)"
.br
.RI "Exits the game when button is clicked twice\&. "
.ti -1c
.RI "void \fBExitToDesktopImmediate\fP ()"
.br
.RI "Immediately exits the game\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "IEnumerator \fBResetExitButton\fP (TextMeshProUGUI text)"
.br
.RI "Resets the text of the exit button after 5 seconds of not clicking it\&. PROBABLY UPDATE WITH AN ANIMATION INSTEAD\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBexitOnClick\fP = false"
.br
.RI "Should the next click of the exit button close the game? "
.ti -1c
.RI "Coroutine \fBexitButtonCoroutine\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Exit\&.ExitToDesktopButton (TextMeshProUGUI text)"

.PP
Exits the game when button is clicked twice\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP Text object to update the value of\&.
.RE
.PP

.nf
18     {
19         if (exitOnClick) { Application\&.Quit(); }
20         else
21         {
22             if (exitButtonCoroutine == null)
23             {
24                 exitButtonCoroutine = StartCoroutine(ResetExitButton(text));
25             }
26         }
27     }
.PP
.fi

.SS "void Exit\&.ExitToDesktopImmediate ()"

.PP
Immediately exits the game\&. 
.nf
32     {
33         Application\&.Quit();
34     }
.PP
.fi

.SS "IEnumerator Exit\&.ResetExitButton (TextMeshProUGUI text)\fR [private]\fP"

.PP
Resets the text of the exit button after 5 seconds of not clicking it\&. PROBABLY UPDATE WITH AN ANIMATION INSTEAD\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.nf
41     {
42         exitOnClick = true;
43         yield return new WaitForSecondsRealtime(5f);
44         text\&.text = "Exit";
45         exitOnClick = false;
46     }
.PP
.fi

.PP
Referenced by \fBExitToDesktopButton()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Coroutine Exit\&.exitButtonCoroutine\fR [private]\fP"

.PP
Referenced by \fBExitToDesktopButton()\fP\&.
.SS "bool Exit\&.exitOnClick = false\fR [private]\fP"

.PP
Should the next click of the exit button close the game? 
.PP
Referenced by \fBExitToDesktopButton()\fP, and \fBResetExitButton()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
