.TH "ExtraSongInfoMenu" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExtraSongInfoMenu
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetText\fP (string songName)"
.br
.RI "sets the text displaying the extra information about the song\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBExtraSongInfoMenu\fP \fBinstance\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "TextMeshProUGUI \fBtext\fP"
.br
.ti -1c
.RI "GameObject \fBchildObjects\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ExtraSongInfoMenu\&.Awake ()\fR [private]\fP"

.nf
11     {
12         if (instance == null) { instance = this; }
13         else { Destroy(this); }
14     }
.PP
.fi

.SS "void ExtraSongInfoMenu\&.SetText (string songName)"

.PP
sets the text displaying the extra information about the song\&. 
.PP
\fBParameters\fP
.RS 4
\fIsongName\fP 
.RE
.PP

.nf
20     {
21         childObjects\&.SetActive(true);
22         SongScore score = GameManager\&.instance\&.selectedSongHighScore;
23         if (score == null) { text\&.text = ""; childObjects\&.SetActive(false);  return; }
24 
25         string newText =
26             $"{songName}\\nScore: {score\&.score}\\nPerfect: {score\&.perfect}\\nGood: {score\&.good}\\nOkay: {score\&.okay}\\nExtra: {score\&.extra}\\nMissed: {score\&.miss}\\nBest Combo: {score\&.highestCombo}/{MidiReadFile\&.CountNotes()}";
27         text\&.text = newText ;
28     }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "GameObject ExtraSongInfoMenu\&.childObjects\fR [private]\fP"

.PP
Referenced by \fBSetText()\fP\&.
.SS "\fBExtraSongInfoMenu\fP ExtraSongInfoMenu\&.instance\fR [static]\fP"

.PP
Referenced by \fBAwake()\fP\&.
.SS "TextMeshProUGUI ExtraSongInfoMenu\&.text\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
