.TH "FileGroupError" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileGroupError \- struct containing information on which files are or aren't located when assembling a file group for a song\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBjson\fP"
.br
.ti -1c
.RI "bool \fBmp3\fP"
.br
.ti -1c
.RI "bool \fBpng\fP"
.br
.ti -1c
.RI "bool \fBmidi\fP"
.br
.ti -1c
.RI "bool \fBscore\fP"
.br
.ti -1c
.RI "bool \fBreplay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct containing information on which files are or aren't located when assembling a file group for a song\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool FileGroupError\&.json"

.SS "bool FileGroupError\&.midi"

.SS "bool FileGroupError\&.mp3"

.SS "bool FileGroupError\&.png"

.SS "bool FileGroupError\&.replay"

.SS "bool FileGroupError\&.score"


.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
