.TH "Assets/Scripts/FileGroup.cs" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/Scripts/FileGroup.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFileGroup\fP"
.br
.RI "Represents a group of files related to a specific song\&. "
.ti -1c
.RI "struct \fBFileGroupError\fP"
.br
.RI "struct containing information on which files are or aren't located when assembling a file group for a song\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
