.TH "GameSettingsMenu" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSettingsMenu
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUsePiano\fP (bool enabled)"
.br
.ti -1c
.RI "void \fBSetUsePedal\fP (bool enabled)"
.br
.ti -1c
.RI "void \fBSetVolume\fP (float volume)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "IEnumerator \fBMonitorMidiConnections\fP ()"
.br
.RI "Checks for active midi connections to the computer every second\&. "
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Toggle \fBusePianoToggle\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "IEnumerator GameSettingsMenu\&.MonitorMidiConnections ()\fR [private]\fP"

.PP
Checks for active midi connections to the computer every second\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.nf
19     {
20         while (true)
21         {
22             
23             CheckMidiDevices(KiboardDebug\&.isMidiConnected);
24             yield return new WaitForSeconds(1);
25         }
26         void CheckMidiDevices(bool midiConnected)
27         {
28             if (usePianoToggle == null) return;
29             usePianoToggle\&.interactable = midiConnected;
30             if (!midiConnected) { usePianoToggle\&.isOn = false; }
31         }
32 
33 
34     }
.PP
.fi

.PP
Referenced by \fBStart()\fP\&.
.SS "void GameSettingsMenu\&.OnDestroy ()\fR [private]\fP"

.nf
51     {
52         StopAllCoroutines();
53     }
.PP
.fi

.SS "void GameSettingsMenu\&.SetUsePedal (bool enabled)"

.nf
41     {
42         GameSettings\&.usePedal = enabled;
43     }
.PP
.fi

.SS "void GameSettingsMenu\&.SetUsePiano (bool enabled)"

.nf
37     {
38         GameSettings\&.usePiano = enabled;
39     }
.PP
.fi

.SS "void GameSettingsMenu\&.SetVolume (float volume)"

.nf
46     {
47         SettingsManager\&.SetVolume(volume);
48     }
.PP
.fi

.SS "void GameSettingsMenu\&.Start ()\fR [private]\fP"

.nf
11     {
12         StartCoroutine(MonitorMidiConnections());
13     }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "Toggle GameSettingsMenu\&.usePianoToggle\fR [private]\fP"

.PP
Referenced by \fBMonitorMidiConnections()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
