.TH "MainMenuLoad" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainMenuLoad
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "IEnumerator \fBLoadToSongSelect\fP ()"
.br
.RI "waits for any player input then loads to song select\&. "
.ti -1c
.RI "IEnumerator \fBFlickerText\fP ()"
.br
.RI "flickers the text "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBdelay\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBtext\fP"
.br
.ti -1c
.RI "Color \fBonColour\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "IEnumerator MainMenuLoad\&.FlickerText ()\fR [private]\fP"

.PP
flickers the text 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.nf
33     {
34         while (true)
35         {
36             text\&.color = onColour;
37             yield return new WaitForSecondsRealtime(delay);
38             text\&.color = Color\&.clear;
39             yield return new WaitForSecondsRealtime(delay);
40         }
41     }
.PP
.fi

.PP
Referenced by \fBStart()\fP\&.
.SS "IEnumerator MainMenuLoad\&.LoadToSongSelect ()\fR [private]\fP"

.PP
waits for any player input then loads to song select\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.nf
24     {
25         yield return new WaitUntil(() => Input\&.anyKeyDown || MidiInput\&.instance\&.GetAnyNoteActive());
26         SceneManager\&.LoadScene("SongSelect", LoadSceneMode\&.Single); // dont use transistion manager because i do not want a fade out\&.
27     }
.PP
.fi

.PP
Referenced by \fBStart()\fP\&.
.SS "void MainMenuLoad\&.Start ()\fR [private]\fP"

.nf
14     {
15         StartCoroutine(FlickerText());
16         StartCoroutine(LoadToSongSelect());
17         
18     }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "float MainMenuLoad\&.delay\fR [private]\fP"

.PP
Referenced by \fBFlickerText()\fP\&.
.SS "Color MainMenuLoad\&.onColour\fR [private]\fP"

.PP
Referenced by \fBFlickerText()\fP\&.
.SS "TextMeshProUGUI MainMenuLoad\&.text\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
