.TH "md__assets_2_documentation_2_markdown_2_modding_01_6_01_customization" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__assets_2_documentation_2_markdown_2_modding_01_6_01_customization \- Modding 
.PP
 Custom Song Image Tags are used to assign images to varying parts of the song\&. Remember that the file name must also be the same as the custom song's folder name\&. For example, to change the icon of the song FurElise, you would name your file \fRicon_FurElise\&.png\fP\&.
.PP
Tag   Description    bg_   Changes the background image when playing the song\&.    icon_   Changes the song icon in song selection\&.   
.SH "UI Image Tags"
.PP
UI Image Tags are used to assign images to certain elements of the players UI in many scenes of the game\&. Each of the following names are split by their in-game scene, which must prefix their desired UI Element\&. For example, the background of the song selection screen must be named \fRSongSelection_Background\&.png\fP\&.
.SS "SongSelection_"
.IP "\(bu" 2
\fBBackground\fP: The background of the song selection screen\&.
.PP
.SS "OtherScene"
.IP "\(bu" 2
\fBBackground\fP: The background of the other scene\&. 
.PP

