.TH "Assets/Scripts/MidiDataHandler.cs" 3 "Version 1.0.0" "KiBoard GDD & Technical Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/Scripts/MidiDataHandler.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMidiDataHandler\fP"
.br
.ti -1c
.RI "class \fBNoteEventDataWrapper\fP"
.br
.RI "Wrapper class for storing BPM and \fBNoteEventInfo\fP data\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KiBoard GDD & Technical Documentation from the source code\&.
